---
title: "human-breast-cancer-analysis"
author: "Melody"
date: "`r Sys.Date()`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---
# Introduction
The dataset used in this vignette is the Xenium human breast cancer.
The data can be accessed here:
<https://www.10xgenomics.com/products/xenium-in-situ/preview-dataset-human-breast>


Details about each file can be found here:
<https://www.10xgenomics.com/support/in-situ-gene-expression/documentation/steps/onboard-analysis/understanding-xenium-outputs#overview>


```{r global options, include = FALSE}
options(width = 80, digits = 3) # output length
knitr::opts_chunk$set(cache = FALSE,echo = TRUE,prompt = FALSE, 
                      comment = NA,message = FALSE,warning = FALSE,
                      fig.align = "center", fig.keep= "all",fig.show ="hold")

# wx=7
#wy=5
```

```{r}
library(jazzPanda)
library(SpatialExperiment)
library(Seurat)
library(ggplot2)
library(data.table)
library(spatstat)
library(dplyr)
library(glmnet)
library(caret)
library(ComplexUpset)
library(corrplot)
library(igraph)
library(ggraph)
library(ggrepel)
library(gridExtra)
library(patchwork)
library(RColorBrewer)
library(ggvenn)
#library(multtest)
#library(metap)
library(scCustomize)
library(tidyr)
library(xtable)
library(limma)
```

```{r}
# calculate peak memory
PEAK_MEM_ID=which(colnames(gc())=="max used")
PEAK_MEM_MB = PEAK_MEM_ID+1

PA = "./analysis/figures/figure5_compare_methods/"
# theme setting for figures
defined_theme <- theme(strip.text = element_text(size = rel(1)),
                      axis.line=element_blank(),
                      axis.ticks=element_blank(),
                      axis.text=element_blank(),
                      legend.position = "none",
                      axis.title=element_blank(),
                      panel.background=element_blank(),
                      panel.grid.major=element_blank(),
                      panel.grid.minor=element_blank(),
                      plot.background=element_blank())

script_path <- rstudioapi::getActiveDocumentContext()$path
script_dir  <- dirname(normalizePath(script_path))
out_dir <- normalizePath(file.path(script_dir, "..", "..",
                                   "figures", "main", "figure5_compare_methods"),
                          mustWork = FALSE)

```

# One sample: CosMx healthy liver
```{r}
#seu_markers = readRDS("cosmx_hhliver_seu_markers.Rds")


chln_jazzPanda_res_lst = readRDS(file.path(script_dir,"/dataset_computational_complexity/cosmx_hhliver_jazzPanda_res_lst.Rds"))
chln_jazzPanda_res = get_top_mg(chln_jazzPanda_res_lst,coef_cutoff=0.2)  
chln_perm_lst = readRDS(file.path(script_dir,"/dataset_computational_complexity/cosmx_hhliver_perm_lst.Rds"))
chln_perm_res = chln_perm_lst$perm.pval.adj
chln_obs_corr = chln_perm_lst$obs.stat
hln_seu=readRDS(file.path(script_dir,"/dataset_computational_complexity/cosmx_hhliver_seu.Rds"))
chln_fit = readRDS(file.path(script_dir,"/dataset_computational_complexity/cosmx_hhliver_fit_cont_obj.Rds"))
chln_vecs= readRDS(file.path(script_dir,"/dataset_computational_complexity/cosmx_hhliver_sq40_vector_lst.Rds"))
hln_seu_markers=readRDS(file.path(script_dir,"/dataset_computational_complexity/cosmx_hhliver_seu_markers.Rds"))


```

```{r fig.width=10, warning=FALSE}
limma_dt<-decideTests(chln_fit) 
for (cl in c("Cholangiocytes", "Hep.4", "Stellate.cells")){
    obs_cutoff = quantile(chln_obs_corr[, cl], 0.75)
    findM_sig =hln_seu_markers[hln_seu_markers$cluster==cl,"gene"]
    limma_sig=row.names(limma_dt[limma_dt[,cl]==1,])
    perm_cl=intersect(row.names(chln_perm_res[chln_perm_res[,cl]<0.05,]),
                 row.names(chln_obs_corr[chln_obs_corr[, cl]>obs_cutoff,]))
    lasso_cl=chln_jazzPanda_res[chln_jazzPanda_res$top_cluster==cl, "gene"]
    df_mt =as.data.frame(matrix(FALSE,nrow=nrow(chln_perm_res),ncol=4))
    row.names(df_mt) =row.names(chln_perm_res)
    colnames(df_mt)=c("jazzPanda-glm",
                      "jazzPanda-correlation",
                        "Wilcoxon Rank Sum Test","limma")
    df_mt[findM_sig,"Wilcoxon Rank Sum Test"] = TRUE
    df_mt[limma_sig,"limma"] = TRUE
    df_mt[perm_cl,"jazzPanda-correlation"] = TRUE

    df_mt[lasso_cl,"jazzPanda-glm"] = TRUE
    
    cl = sub(cl, pattern = ".cells", replacement="")
    pdf(file.path(out_dir, paste0(cl, "_cosmx_hhliver_upset.pdf", sep="")), width=4, height=4)
    plot(upset(df_mt,
              intersect=c("limma","Wilcoxon Rank Sum Test", 
                          "jazzPanda-correlation","jazzPanda-glm"),
              wrap=TRUE, keep_empty_groups= FALSE, name="",
              themes=theme_grey(),
              stripes=upset_stripes(geom=geom_segment(size=5),colors=c('grey95', 'grey95', 'grey95')),
              sort_intersections_by ="cardinality", sort_sets= FALSE,min_degree=1,
              set_sizes = FALSE,

               sort_intersections= "descending", warn_when_converting=FALSE,
               warn_when_dropping_groups=TRUE,encode_sets=TRUE,
              matrix=(intersection_matrix()+theme(axis.text.x=element_blank(),panel.background = element_rect(fill="NA"),
                                                  axis.ticks = element_blank(),
                                                  axis.title = element_blank())),
               base_annotations=list('Intersection size'=(intersection_size(bar_number_threshold=1,color='grey9',fill='grey80',
                                                                            text = list(size = 3, vjust = -0.1))+ 
                                                            theme(axis.text.x = element_blank(),axis.title.x = element_blank(),
                                                                  panel.background = element_rect(fill="NA"),
                                                                  panel.grid = element_line(color="grey90"),
                                                                  axis.ticks.x = element_blank()))),
              width_ratio=0.5, height_ratio=1/4)+
           ggtitle(paste(cl,"cells"))
         )
    dev.off()
}
```

```{r}

cor_M = cor(chln_vecs$gene_mt,
            chln_vecs$cluster_mt,method = "spearman")
cor_M[cor_M <= 0.7] = 0
cor_M[cor_M > 0.7]=1

for (cl in c("Cholangiocytes", "Hep.4", "Stellate.cells")){
    obs_cutoff = quantile(chln_obs_corr[, cl], 0.75)
    fm_cl=FindMarkers(hln_seu, ident.1 = cl, only.pos = TRUE,
            logfc.threshold = 0.25)
    fm_cl = fm_cl[order(fm_cl$avg_log2FC, decreasing = TRUE),]
    to_plot =row.names(fm_cl)
    FM_pt = data.frame("name"=to_plot,"rk"= 1:length(to_plot),
                   "y"= cumsum(cor_M[to_plot, cl]),
                   "type"="FindMarkers")
    limma_cl=limma_dt[limma_dt[,cl]==1,]
    
    limma_cl<-topTable(chln_fit,coef=cl,p.value = 0.05, n=Inf, sort.by = "p")
    limma_cl = limma_cl[limma_cl$logFC>0, ]
    to_plot_lm = row.names(limma_cl)
    
    perm_cl=intersect(row.names(chln_perm_res[chln_perm_res[,cl]<0.05,]),
                 row.names(chln_obs_corr[chln_obs_corr[, cl]>obs_cutoff,]))
    rounded_val=signif(as.numeric(chln_obs_corr[perm_cl,cl]), digits = 3)
    perm_sorted = as.data.frame(cbind(gene=perm_cl, value=rounded_val))
    perm_sorted$value = as.numeric(perm_sorted$value)
    perm_sorted=perm_sorted[order(perm_sorted$value, decreasing = TRUE),]

    
    lasso_sig = chln_jazzPanda_res[chln_jazzPanda_res$top_cluster==cl,]
    lasso_sig = lasso_sig[order(lasso_sig$glm_coef, decreasing = TRUE),]
    lasso_pt = data.frame("name"=lasso_sig$gene,"rk"= 1:nrow(lasso_sig),
                   "y"= cumsum(cor_M[lasso_sig$gene, cl]),
                   "type"="jazzPanda-glm")
    
    limma_pt = data.frame("name"=to_plot_lm,"rk"= 1:length(to_plot_lm),
                   "y"= cumsum(cor_M[to_plot_lm, cl]),
                   "type"="limma")
    
    corr_pt = data.frame("name"=perm_sorted$gene,"rk"= 1:length(perm_sorted$gene),
                   "y"= cumsum(cor_M[perm_sorted$gene, cl]),
                   "type"="jazzPanda-correlation")
  
    #data_lst = rbind(limma_pt, lasso_pt,FM_pt)
    data_lst = rbind(limma_pt, FM_pt,corr_pt,lasso_pt)
    data_lst$type = factor(data_lst$type)
    data_lst$rk = as.numeric(data_lst$rk)
    pdf(file.path(out_dir, paste0(cl, "_cosmx_hhliver_rank.pdf")), width=5, height=5)
    plot(y~rk,data=data_lst[data_lst$type=="limma",],
        type="s", xlim=c(0,max(data_lst$rk)),main=paste(cl, " cells",sep=""),
        ylim=c(0,max(data_lst$y)),xlab="Rank of marker genes",
        ylab="Cumulative count of genes with correlation >0.7"
        )
    lines(y~rk,data=data_lst[data_lst$type=="FindMarkers",],type="s",col="blue")
     lines(y~rk,data=data_lst[data_lst$type=="jazzPanda-correlation",],type="s",col="orange")
     lines(y~rk,data=data_lst[data_lst$type=="jazzPanda-glm",],type="s",col="red")
    legend("bottomright",           
         legend = c("limma","Wilcoxon Rank Sum Test", 
                    "jazzPanda-correlation","jazzPanda-glm"),  
         col = c("black", "blue", "orange","red"),   
         lty = 1,             
         cex = 0.8)   
     dev.off()
}
```

# Two samples: Xenium human breast 
```{r}

xhb_glm_lst = readRDS(file.path(script_dir,
                                   "dataset_computational_complexity/xenium_hbreast_jazzPanda_res_lst.Rds"))
xhb_jazzPanda_res = get_top_mg(xhb_glm_lst,coef_cutoff=0.2)  
xhb_fm=readRDS(file.path(script_dir,"dataset_computational_complexity/xenium_hbreast_seu_markers.Rds"))
xhb_seu=readRDS(file.path(script_dir,"dataset_computational_complexity/xenium_hbreast_seu.Rds"))
xhb_fit = readRDS(file.path(script_dir,"dataset_computational_complexity/xenium_hbreast_fit_cont_obj.Rds"))
xhb_vecs= readRDS(file.path(script_dir,"dataset_computational_complexity/xenium_hbreast_sq40_vector_lst.Rds"))
xhb_clusters= readRDS(file.path(script_dir,"dataset_computational_complexity/xenium_hbreast_clusters.Rds"))

```

```{r fig.width=10, warning=FALSE}
limma_dt<-decideTests(xhb_fit)
panel_genes=row.names(xhb_seu)
for (cl in c("c1", "c8","c5")){
    anno_name = unique(xhb_clusters[xhb_clusters$cluster==cl,"anno"])
    anno_name = sub(anno_name,pattern = "_Cells", replacement="")
    limma_sig=row.names(limma_dt[limma_dt[,cl]==1,])
  
    findM_sig =xhb_fm[xhb_fm$cluster==cl,"gene"]
    lasso_sig = xhb_jazzPanda_res[xhb_jazzPanda_res$top_cluster==cl,"gene"]
  
    data_lst = list("limma"=limma_sig,
                    "Wilcoxon Rank Sum Test" =findM_sig,
                    "jazzPanda-glm"=lasso_sig)

    df_mt =as.data.frame(matrix(FALSE,nrow=length(panel_genes),ncol=3))
    row.names(df_mt) =panel_genes
    colnames(df_mt)=c("jazzPanda-glm", "Wilcoxon Rank Sum Test",
                      "limma")
    df_mt[findM_sig,"Wilcoxon Rank Sum Test"] = TRUE
    df_mt[limma_sig,"limma"] = TRUE
    df_mt[lasso_sig,"jazzPanda-glm"] = TRUE
    df_mt$gene_name =row.names(df_mt)
    pdf(file.path(out_dir, paste0(anno_name, "_xenium_hbreast_upset.pdf")), width=4, height=4)
    plot(upset(df_mt,
              intersect=c("limma","Wilcoxon Rank Sum Test", "jazzPanda-glm"),
              wrap=TRUE, keep_empty_groups= FALSE, name="",
              themes=theme_grey(),
              stripes=upset_stripes(geom=geom_segment(size=5),colors=c('grey95', 'grey95', 'grey95')),
              sort_intersections_by ="cardinality", sort_sets= FALSE,min_degree=1,
              set_sizes = FALSE,
               sort_intersections= "descending", warn_when_converting=FALSE,
               warn_when_dropping_groups=TRUE,encode_sets=TRUE,
              matrix=(intersection_matrix()+theme(axis.text.x=element_blank(),panel.background = element_rect(fill="NA"),
                                                  axis.ticks = element_blank(),
                                                  axis.title = element_blank())),
               base_annotations=list('Intersection size'=(intersection_size(bar_number_threshold=1,color='grey9',fill='grey80',
                                                                            text = list(size = 3, vjust = -0.1))+ 
                                                            theme(axis.text.x = element_blank(),axis.title.x = element_blank(),
                                                                  panel.background = element_rect(fill="NA"),
                                                                  panel.grid = element_line(color="grey90"),
                                                                  axis.ticks.x = element_blank()))),
              width_ratio=0.5, height_ratio=1/4)+
           ggtitle(paste(anno_name,"cells"))
         )
    dev.off()
}
```



```{r}

cor_M = cor(xhb_vecs$gene_mt,
            xhb_vecs$cluster_mt,method = "spearman")
cor_M[cor_M <= 0.7] = 0
cor_M[cor_M > 0.7]=1

cluster_names= colnames(limma_dt)
for (cl in c("c1", "c8", "c5")){
    anno_name = unique(xhb_clusters[xhb_clusters$cluster==cl,"anno"])
    anno_name = sub(anno_name,pattern = "_Cells", replacement="")
    fm_cl=FindMarkers(xhb_seu, ident.1 = cl, only.pos = TRUE,
            logfc.threshold = 0.25)
    fm_cl = fm_cl[order(fm_cl$avg_log2FC, decreasing = TRUE),]
    to_plot =row.names(fm_cl)
    FM_pt = data.frame("name"=to_plot,"rk"= 1:length(to_plot),
                   "y"= cumsum(cor_M[to_plot, cl]),
                   "type"="FindMarkers")
    
    limma_cl<-topTable(xhb_fit,coef=cl,p.value = 0.05, n=Inf, sort.by = "p")
    limma_cl = limma_cl[limma_cl$logFC>0, ]
    to_plot_lm = row.names(limma_cl)
    
    
    lasso_sig = xhb_jazzPanda_res[xhb_jazzPanda_res$top_cluster==cl,]
    lasso_sig = lasso_sig[order(lasso_sig$glm_coef, decreasing = TRUE),]
    
    limma_pt = data.frame("name"=to_plot_lm,"rk"= 1:length(to_plot_lm),
                   "y"= cumsum(cor_M[to_plot_lm, cl]),
                   "type"="limma")
    
    lasso_pt = data.frame("name"=lasso_sig$gene,"rk"= 1:nrow(lasso_sig),
                   "y"= cumsum(cor_M[lasso_sig$gene, cl]),
                   "type"="jazzPanda-glm")
  
  
    data_lst = rbind(limma_pt, lasso_pt,FM_pt)
    data_lst$type = factor(data_lst$type)
    data_lst$rk = as.numeric(data_lst$rk)
    pdf(file.path(out_dir, paste0(anno_name, "_xenium_hbreast_rank.pdf")), width=5, height=5)
    plot(y~rk,data=data_lst[data_lst$type=="limma",],
        type="s", xlim=c(0,max(data_lst$rk)),main=paste(anno_name, " cells",sep=""),
        ylim=c(0,max(data_lst$y)),xlab="Rank of marker genes",
        ylab="Cumulative count of genes with correlation >0.7"
        )
    lines(y~rk,data=data_lst[data_lst$type=="FindMarkers",],type="s",col="blue")
     lines(y~rk,data=data_lst[data_lst$type=="jazzPanda-glm",],type="s",col="red")
    legend("bottomright",           
         legend = c("limma","Wilcoxon Rank Sum Test", "jazzPanda-glm"),  
         col = c("black", "blue", "red"),   
         lty = 1,             
         cex = 0.8)   
     dev.off()
}
```