---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ggplot2)
library(ggpubr)
library(ggrepel)
library(gridExtra)
library(matrixStats)
library(patchwork)
library(pheatmap)
library(Seurat)
library(RColorBrewer)
library(reshape2)
library(jazzPanda)
library(tidyr)
library(dplyr)
library(corrplot)
library(edgeR)
library(ComplexUpset)
library(dplyr)
library(spatstat)

# theme setting for figures
defined_theme <- theme(
  strip.text = element_text(size = rel(1.8)),
  axis.line=element_blank(),
  axis.ticks=element_blank(),
  axis.text=element_blank(),
  legend.position = "bottom",
  axis.title=element_blank(),
  #strip.background = element_rect(fill="white",colour = "black"),
  strip.background = element_blank(),
  panel.background=element_blank(),
  panel.grid.major=element_blank(),
  panel.grid.minor=element_blank(),
  plot.background=element_blank())
```

```{r}
PA = "figures/main/figure4_simulation/"
```

## cluster sizses versus number of significant genes 
### load clusters 
```{r}
# load clusters
library(matrixStats)
library(Seurat)
library(reshape2)
library(jazzPanda)
library(tidyr)
library(dplyr)
# read in SOMACollection
seu <- readRDS("/vast/projects/xenium_5k/data/jazzPanda_paper_dataset/CosMx_normal_and_diseased_liver_samples/LiverDataReleaseSeurat_newUMAP.RDS")
# local cell metadata
metadata <- as.data.frame(seu@meta.data)
cat("Number of cells in cancer and normal samples: ",nrow(metadata))
## remove low quality cells
qc_cols <- c("qcFlagsRNACounts", "qcFlagsCellCounts", "qcFlagsCellPropNeg",
             "qcFlagsCellComplex", "qcFlagsCellArea","qcFlagsFOV")
metadata <- metadata[!apply(metadata[, qc_cols], 1, function(x) any(x == "Fail")), ]
cat("Total number of cells remaining after removing low quality cells: ", nrow(metadata))


cell_info_cols = c("x_FOV_px", "y_FOV_px", "x_slide_mm", "y_slide_mm",
                   "nCount_negprobes","nFeature_negprobes","nCount_falsecode",
                   "nFeature_falsecode","slide_ID_numeric", "Run_Tissue_name",
                   "fov","cellType","niche", "cell_id")
cellCoords <- metadata[, cell_info_cols]
px_to_mm <- function(data){
    all_fv = unique(data$fov)
    parm_df = as.data.frame(matrix(0, ncol=5, nrow=length(all_fv)))
    colnames(parm_df) = c("fov","y_slope","y_intcp","x_slope","x_intcp")
    parm_df$fov = all_fv
    for (fv in all_fv){
        curr_fov = data[data$fov == fv, ]
        curr_fov = curr_fov[order(curr_fov$x_FOV_px), ]
        curr_fov = curr_fov[c(1, nrow(curr_fov)), ]
        curr_fov = curr_fov[c(1,2),c("y_slide_mm","x_slide_mm","y_FOV_px","x_FOV_px") ]
        # mm to px for y
        y_slope = (curr_fov[2,"y_slide_mm"] - curr_fov[1,"y_slide_mm"]) / (curr_fov[2,"y_FOV_px"] - curr_fov[1,"y_FOV_px"])
        y_intcp = curr_fov[2,"y_slide_mm"]- (y_slope*curr_fov[2,"y_FOV_px"])
        # mm to px for x
        x_slope = (curr_fov[2,"x_slide_mm"] - curr_fov[1,"x_slide_mm"]) / (curr_fov[2,"x_FOV_px"] - curr_fov[1,"x_FOV_px"])
        x_intcp = curr_fov[2,"x_slide_mm"]- (x_slope*curr_fov[2,"x_FOV_px"])
        parm_df[parm_df$fov==fv,"y_slope"] = y_slope
        parm_df[parm_df$fov==fv,"y_intcp"] = y_intcp
        parm_df[parm_df$fov==fv,"x_slope"] = x_slope
        parm_df[parm_df$fov==fv,"x_intcp"] = x_intcp
    }
    return (parm_df)
    
}

# number of cells per fov
# all fovs contain at least 2 cells
fov_summary = as.data.frame(table(cellCoords[cellCoords$slide_ID_numeric==2,"fov"]))

# keep cancer tissue only
liver_cancer = cellCoords[cellCoords$slide_ID_numeric==2 ,]

# caculate the slope and intercept parameters for each fov
parm_df = px_to_mm(liver_cancer)

# refine clustering
selected_cols = c("x_FOV_px", "y_FOV_px","x_slide_mm", "y_slide_mm", "slide_ID_numeric", "Run_Tissue_name", "fov","cellType","niche" )
clusters_info = cellCoords[cellCoords$slide_ID_numeric=="2" & (row.names(cellCoords) %in% row.names(metadata)),selected_cols ]

colnames(clusters_info) =c("x_FOV_px","y_FOV_px" , "x", "y", 
                           "slide_ID_numeric", "Run_Tissue_name", 
                           "fov","cellTypes","niche")
clusters_info$cluster = as.character(clusters_info$cellTypes)
clusters_info[clusters_info$cellTypes %in% c("Antibody.secreting.B.cells", "Mature.B.cells"),"cluster"] = "B"
clusters_info[clusters_info$cellTypes %in% c("CD3+.alpha.beta.T.cells", "gamma.delta.T.cells.1"),"cluster"] = "T"
clusters_info[clusters_info$cellTypes %in% c("Non.inflammatory.macrophages", "Inflammatory.macrophages"),"cluster"] = "Macrophages"
# clusters_info[clusters_info$cellTypes %in% c("Hep.3","Hep.4", "Hep.5","Hep.6"),"cluster"] = "Hep3"
ig_clusters = c("NotDet")

clusters_info = clusters_info[clusters_info$cluster != "NotDet",]
colnames(clusters_info)[10] = "anno"
clusters_info$anno = factor(clusters_info$anno,
                            levels=c("tumor_1","tumor_2","Macrophages","T",
                                     "Periportal.LSECs","Stellate.cells","B",
                                     "Central.venous.LSECs","Cholangiocytes","Hep",
                                     "Portal.endothelial.cells",
                                     "NK.like.cells","Erthyroid.cells"))
clusters_info$cluster =  paste("c",as.numeric(factor(clusters_info$anno)), sep="")
clusters_info$cluster =factor(clusters_info$cluster, levels=paste("c",1:13, sep=""))
clusters_info$cell_id = row.names(clusters_info)

clusters_info$sample = "cancer"
# dim = 332873     11
clusters_info = clusters_info[!duplicated(clusters_info[,c("x","y")]),]
clusters_info$x = clusters_info$x * 1000
clusters_info$y = clusters_info$y * 1000

plt_dff = as.data.frame(table(clusters_info$cluster))
colnames(plt_dff) = c("cluster", "ncells")

nsig_df = as.data.frame(colSums(adjp_df[, 1:13] <0.05))
colnames(nsig_df) = c("nsig")
nsig_df$cluster = row.names(nsig_df)

dff = merge(plt_dff, nsig_df, by="cluster")
dff$log_ncells = log10(dff$ncells)
cl_anno = as.data.frame(unique(clusters_info[,c("anno","cluster")]))
dff = merge(dff, cl_anno, by="cluster")
dff$cluster = as.character(dff$cluster)
dff$anno = as.character(dff$anno)
dff = rbind(dff, c("falsecode", 0, 0, 0, "falsecode"), 
            c("negprobe", 0, 0, 0, "negprobe"))

write.csv(dff, "cosmx_hlc_cluster_size_celltype_label.csv")

```

```{r}
dff = read.csv("cosmx_hlc_cluster_size_celltype_label.csv", row.names = 1)
dff = dff[order(dff$ncells, decreasing = TRUE),]
p1<- ggplot(dff, aes(x = log_ncells, y = nsig, color = anno)) +
  geom_point(size = 5) +
  # geom_bar()+
   # geom_boxplot(outlier.size = 0.8, outlier.alpha = 0.5, width = 0.6)+
    #geom_violin(scale = "width")+
  theme_classic() +
    labs(title = " ", x = " log(Cluster size)",
         y = "Number of significant genes", color="cell type") +
  theme(axis.line = element_blank(),
         legend.title=  element_text(size=12),
        legend.text=  element_text(size=12),
         panel.border = element_rect(color = "black", fill = NA, linewidth = 0.6),
        axis.text.y = element_text(size=12, vjust=0.5),
        
         axis.text.x = element_text(size = 12, hjust = 0.5),
        axis.title.y= element_text(size=12))

pdf(paste(PA, "S_ncells_ngenes_scatter.pdf", sep=""), width=7, height=4)
p1
dev.off()
```

## pvalue versus correlation
```{r}
library(tidyverse)

adjp_long <- adjp_df[, 1:13] %>%
  rownames_to_column("gene") %>%
  pivot_longer(-gene, names_to = "cluster", values_to = "p_adj")

obs_long <- obs_df[, 1:13] %>%
  rownames_to_column("gene") %>%
  pivot_longer(-gene, names_to = "cluster", 
               values_to = "statistic")

merged_df <- left_join(adjp_long, obs_long, by = c("gene", "cluster"))

merged_df <- merged_df %>%
  mutate(log_padj = -log10(p_adj),
         flag_low_effect = p_adj < 0.05 & statistic > 0.05)  
merged_df$label = "Not significant"
merged_df[merged_df$flag_low_effect==TRUE,"label"] ="Significant"
merged_df$label = factor(merged_df$label, 
                         levels=c("Significant", "Not significant"))
merged_df$cluster=factor(merged_df$cluster, levels = c(
  "c1", "c2", "c3", "c4", "c5", "c6", "c7", "c8", "c9", 
  "c10", "c11", "c12", "c13", "falsecode", "negprobe"
))


merged_df = merge(merged_df, dff[, c("cluster","anno")], by="cluster")
merged_df$anno = factor(merged_df$anno, levels = dff$anno)
merged_df = merged_df[order(merged_df$anno),]


x_thresh <- 0.05
y_thresh <- -log10(0.05)

merged_df <- merged_df %>%
  mutate(
    quadrant = case_when(
      statistic <= x_thresh & log_padj >= y_thresh ~ "Q1",  # Top-left
      statistic >  x_thresh & log_padj >= y_thresh ~ "Q2",  # Top-right
      TRUE ~ "Other"
    )
  )

anno_levels <- unique(merged_df$anno)

all_combos <- expand_grid(
  anno = anno_levels,
  quadrant = c("Q1", "Q2")
)

quad_counts <- merged_df %>%
    
  filter(quadrant %in% c("Q1", "Q2")) %>%

  group_by(anno, quadrant) %>%
         
  summarise(n = n(), .groups = "drop") %>%
 right_join(all_combos, by = c("anno", "quadrant")) %>%
  mutate(n = replace_na(n, 0))

# Merge counts with positions
quad_counts <- quad_counts %>%
  left_join(label_positions, by = "quadrant")

pdf(paste(PA, "pval_vs_correlation_scatter.pdf",sep=""), 
    width=18, height=14)
ggplot(merged_df, aes(x = statistic, y = log_padj,color=label)) +
  geom_point(alpha = 0.6, size=0.01) +
    facet_wrap(~anno, ncol=4)+
    scale_color_manual(values=c("steelblue","black"))+
    scale_y_continuous(breaks = c(0, 1,-log10(0.05), 2,3), 
                       labels = c("0","1","-log10(0.05)","2","3"))+
    scale_x_continuous(limits = c(-0.25, 0.2),
                       breaks = c(-0.25,-0.1, 0, 0.05, 0.1, 0.2), 
                       labels = c(-0.25,-0.1,0, 0.05, 0.1, 0.2))+
  geom_hline(yintercept = -log10(0.05), color = "grey", linetype = "dashed") +
  geom_vline(xintercept = 0.05, color = "grey", linetype = "dashed") +
    geom_label(data = quad_counts,
               aes(x = x, y = y, label = n), inherit.aes = FALSE, size = 4,
               label.size = 0.3, label.r = unit(0.1, "lines"), fill = "white",   
               color = "black"    ) +
  labs(x = "correlation", y = "-log10(adjusted p-value)"
       ) +
        guides(colour = guide_legend(override.aes = list(size=4,alpha=1)))+
  theme_minimal(base_size = 13) +
  theme(panel.border = element_rect(color = "black", 
                                    fill = NA, linewidth = 0.6),
    legend.position = "top", legend.title = element_blank(),
    legend.text = element_text(size = 15),
    axis.title = element_text(size = 16),
     strip.text = element_text(size =16),
    axis.text = element_text(size = 12),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(),
    plot.title = element_text(face = "bold", size = 14)
  )
dev.off()
```


## cluster sizses versus number of significant genes 
### load clusters 
```{r}
# load clusters
library(matrixStats)
library(Seurat)
library(reshape2)
library(jazzPanda)
library(tidyr)
library(dplyr)
# read in SOMACollection
seu <- readRDS("/vast/projects/xenium_5k/data/cosmx_hliver/LiverDataReleaseSeurat_newUMAP.RDS")
# local cell metadata
metadata <- as.data.frame(seu@meta.data)
cat("Number of cells in cancer and normal samples: ",nrow(metadata))
## remove low quality cells
qc_cols <- c("qcFlagsRNACounts", "qcFlagsCellCounts", "qcFlagsCellPropNeg",
             "qcFlagsCellComplex", "qcFlagsCellArea","qcFlagsFOV")
metadata <- metadata[!apply(metadata[, qc_cols], 1, function(x) any(x == "Fail")), ]
cat("Total number of cells remaining after removing low quality cells: ", nrow(metadata))


cell_info_cols = c("x_FOV_px", "y_FOV_px", "x_slide_mm", "y_slide_mm",
                   "nCount_negprobes","nFeature_negprobes","nCount_falsecode",
                   "nFeature_falsecode","slide_ID_numeric", "Run_Tissue_name",
                   "fov","cellType","niche", "cell_id")
cellCoords <- metadata[, cell_info_cols]
px_to_mm <- function(data){
    all_fv = unique(data$fov)
    parm_df = as.data.frame(matrix(0, ncol=5, nrow=length(all_fv)))
    colnames(parm_df) = c("fov","y_slope","y_intcp","x_slope","x_intcp")
    parm_df$fov = all_fv
    for (fv in all_fv){
        curr_fov = data[data$fov == fv, ]
        curr_fov = curr_fov[order(curr_fov$x_FOV_px), ]
        curr_fov = curr_fov[c(1, nrow(curr_fov)), ]
        curr_fov = curr_fov[c(1,2),c("y_slide_mm","x_slide_mm","y_FOV_px","x_FOV_px") ]
        # mm to px for y
        y_slope = (curr_fov[2,"y_slide_mm"] - curr_fov[1,"y_slide_mm"]) / (curr_fov[2,"y_FOV_px"] - curr_fov[1,"y_FOV_px"])
        y_intcp = curr_fov[2,"y_slide_mm"]- (y_slope*curr_fov[2,"y_FOV_px"])
        # mm to px for x
        x_slope = (curr_fov[2,"x_slide_mm"] - curr_fov[1,"x_slide_mm"]) / (curr_fov[2,"x_FOV_px"] - curr_fov[1,"x_FOV_px"])
        x_intcp = curr_fov[2,"x_slide_mm"]- (x_slope*curr_fov[2,"x_FOV_px"])
        parm_df[parm_df$fov==fv,"y_slope"] = y_slope
        parm_df[parm_df$fov==fv,"y_intcp"] = y_intcp
        parm_df[parm_df$fov==fv,"x_slope"] = x_slope
        parm_df[parm_df$fov==fv,"x_intcp"] = x_intcp
    }
    return (parm_df)
    
}

# number of cells per fov
# all fovs contain at least 2 cells
fov_summary = as.data.frame(table(cellCoords[cellCoords$slide_ID_numeric==2,"fov"]))

# keep cancer tissue only
liver_cancer = cellCoords[cellCoords$slide_ID_numeric==2 ,]

# caculate the slope and intercept parameters for each fov
parm_df = px_to_mm(liver_cancer)

# refine clustering
selected_cols = c("x_FOV_px", "y_FOV_px","x_slide_mm", "y_slide_mm", "slide_ID_numeric", "Run_Tissue_name", "fov","cellType","niche" )
clusters_info = cellCoords[cellCoords$slide_ID_numeric=="2" & (row.names(cellCoords) %in% row.names(metadata)),selected_cols ]

colnames(clusters_info) =c("x_FOV_px","y_FOV_px" , "x", "y", 
                           "slide_ID_numeric", "Run_Tissue_name", 
                           "fov","cellTypes","niche")
clusters_info$cluster = as.character(clusters_info$cellTypes)
clusters_info[clusters_info$cellTypes %in% c("Antibody.secreting.B.cells", "Mature.B.cells"),"cluster"] = "B"
clusters_info[clusters_info$cellTypes %in% c("CD3+.alpha.beta.T.cells", "gamma.delta.T.cells.1"),"cluster"] = "T"
clusters_info[clusters_info$cellTypes %in% c("Non.inflammatory.macrophages", "Inflammatory.macrophages"),"cluster"] = "Macrophages"
# clusters_info[clusters_info$cellTypes %in% c("Hep.3","Hep.4", "Hep.5","Hep.6"),"cluster"] = "Hep3"
ig_clusters = c("NotDet")

clusters_info = clusters_info[clusters_info$cluster != "NotDet",]
colnames(clusters_info)[10] = "anno"
clusters_info$anno = factor(clusters_info$anno,
                            levels=c("tumor_1","tumor_2","Macrophages","T",
                                     "Periportal.LSECs","Stellate.cells","B",
                                     "Central.venous.LSECs","Cholangiocytes","Hep",
                                     "Portal.endothelial.cells",
                                     "NK.like.cells","Erthyroid.cells"))
clusters_info$cluster =  paste("c",as.numeric(factor(clusters_info$anno)), sep="")
clusters_info$cluster =factor(clusters_info$cluster, levels=paste("c",1:13, sep=""))
clusters_info$cell_id = row.names(clusters_info)

clusters_info$sample = "cancer"
# dim = 332873     11
clusters_info = clusters_info[!duplicated(clusters_info[,c("x","y")]),]
clusters_info$x = clusters_info$x * 1000
clusters_info$y = clusters_info$y * 1000

plt_dff = as.data.frame(table(clusters_info$cluster))
colnames(plt_dff) = c("cluster", "ncells")

nsig_df = as.data.frame(colSums(adjp_df[, 1:13] <0.05))
colnames(nsig_df) = c("nsig")
nsig_df$cluster = row.names(nsig_df)

dff = merge(plt_dff, nsig_df, by="cluster")
dff$log_ncells = log10(dff$ncells)
cl_anno = as.data.frame(unique(clusters_info[,c("anno","cluster")]))
dff = merge(dff, cl_anno, by="cluster")
dff$cluster = as.character(dff$cluster)
dff$anno = as.character(dff$anno)
dff = rbind(dff, c("falsecode", 0, 0, 0, "falsecode"), 
            c("negprobe", 0, 0, 0, "negprobe"))

write.csv(dff, "cosmx_hlc_cluster_size_celltype_label.csv")

```

```{r}
dff = read.csv("cosmx_hlc_cluster_size_celltype_label.csv", row.names = 1)
dff = dff[order(dff$ncells, decreasing = TRUE),]
p1<- ggplot(dff, aes(x = log_ncells, y = nsig, color = anno)) +
  geom_point(size = 5) +
  # geom_bar()+
   # geom_boxplot(outlier.size = 0.8, outlier.alpha = 0.5, width = 0.6)+
    #geom_violin(scale = "width")+
  theme_classic() +
    labs(title = " ", x = " log(Cluster size)",
         y = "Number of significant genes", color="cell type") +
  theme(axis.line = element_blank(),
         legend.title=  element_text(size=12),
        legend.text=  element_text(size=12),
         panel.border = element_rect(color = "black", fill = NA, linewidth = 0.6),
        axis.text.y = element_text(size=12, vjust=0.5),
        
         axis.text.x = element_text(size = 12, hjust = 0.5),
        axis.title.y= element_text(size=12))

pdf(paste(PA, "S_ncells_ngenes_scatter.pdf", sep=""), width=7, height=4)
p1
dev.off()
```

## pvalue versus correlation
```{r}
library(tidyverse)

adjp_long <- adjp_df[, 1:13] %>%
  rownames_to_column("gene") %>%
  pivot_longer(-gene, names_to = "cluster", values_to = "p_adj")

obs_long <- obs_df[, 1:13] %>%
  rownames_to_column("gene") %>%
  pivot_longer(-gene, names_to = "cluster", 
               values_to = "statistic")

merged_df <- left_join(adjp_long, obs_long, by = c("gene", "cluster"))

merged_df <- merged_df %>%
  mutate(log_padj = -log10(p_adj),
         flag_low_effect = p_adj < 0.05 & statistic > 0.05)  
merged_df$label = "Not significant"
merged_df[merged_df$flag_low_effect==TRUE,"label"] ="Significant"
merged_df$label = factor(merged_df$label, 
                         levels=c("Significant", "Not significant"))
merged_df$cluster=factor(merged_df$cluster, levels = c(
  "c1", "c2", "c3", "c4", "c5", "c6", "c7", "c8", "c9", 
  "c10", "c11", "c12", "c13", "falsecode", "negprobe"
))


merged_df = merge(merged_df, dff[, c("cluster","anno")], by="cluster")
merged_df$anno = factor(merged_df$anno, levels = dff$anno)
merged_df = merged_df[order(merged_df$anno),]


x_thresh <- 0.05
y_thresh <- -log10(0.05)

merged_df <- merged_df %>%
  mutate(
    quadrant = case_when(
      statistic <= x_thresh & log_padj >= y_thresh ~ "Q1",  # Top-left
      statistic >  x_thresh & log_padj >= y_thresh ~ "Q2",  # Top-right
      TRUE ~ "Other"
    )
  )

anno_levels <- unique(merged_df$anno)

all_combos <- expand_grid(
  anno = anno_levels,
  quadrant = c("Q1", "Q2")
)

quad_counts <- merged_df %>%
    
  filter(quadrant %in% c("Q1", "Q2")) %>%

  group_by(anno, quadrant) %>%
         
  summarise(n = n(), .groups = "drop") %>%
 right_join(all_combos, by = c("anno", "quadrant")) %>%
  mutate(n = replace_na(n, 0))

# Merge counts with positions
quad_counts <- quad_counts %>%
  left_join(label_positions, by = "quadrant")

pdf(paste(PA, "pval_vs_correlation_scatter.pdf",sep=""), 
    width=18, height=14)
ggplot(merged_df, aes(x = statistic, y = log_padj,color=label)) +
  geom_point(alpha = 0.6, size=0.01) +
    facet_wrap(~anno, ncol=4)+
    scale_color_manual(values=c("steelblue","black"))+
    scale_y_continuous(breaks = c(0, 1,-log10(0.05), 2,3), 
                       labels = c("0","1","-log10(0.05)","2","3"))+
    scale_x_continuous(limits = c(-0.25, 0.2),
                       breaks = c(-0.25,-0.1, 0, 0.05, 0.1, 0.2), 
                       labels = c(-0.25,-0.1,0, 0.05, 0.1, 0.2))+
  geom_hline(yintercept = -log10(0.05), color = "grey", linetype = "dashed") +
  geom_vline(xintercept = 0.05, color = "grey", linetype = "dashed") +
    geom_label(data = quad_counts,
               aes(x = x, y = y, label = n), inherit.aes = FALSE, size = 4,
               label.size = 0.3, label.r = unit(0.1, "lines"), fill = "white",   
               color = "black"    ) +
  labs(x = "correlation", y = "-log10(adjusted p-value)"
       ) +
        guides(colour = guide_legend(override.aes = list(size=4,alpha=1)))+
  theme_minimal(base_size = 13) +
  theme(panel.border = element_rect(color = "black", 
                                    fill = NA, linewidth = 0.6),
    legend.position = "top", legend.title = element_blank(),
    legend.text = element_text(size = 15),
    axis.title = element_text(size = 16),
     strip.text = element_text(size =16),
    axis.text = element_text(size = 12),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(),
    plot.title = element_text(face = "bold", size = 14)
  )
dev.off()
```