---
title: "Xenium human lung cancer sample 1"
author: "Melody Jin"
date: "2025-09-08"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: false
editor_options:
  chunk_output_type: console
---

```{r global-options, include = FALSE}
options(width = 80 , digits = 3) # output length

knitr::opts_chunk$set(cache = FALSE,echo = TRUE,prompt = FALSE, 
                      comment = NA,message = FALSE,warning = FALSE,
                      fig.align = "center", fig.keep= "all",fig.show ="hold")

```

```{r load-lib}
library(jazzPanda)
library(SpatialExperiment)
library(Seurat)
library(ggplot2)
library(data.table)
library(dplyr)
library(tidyr)
library(glmnet)
library(caret)
library(ComplexUpset)
library(ggrepel)
library(gridExtra)
library(patchwork)
library(RColorBrewer)
library(limma)
library(here)
library(data.table)
library(xtable)
source(here("scripts/utils.R"))

```

# load the data
```{r load-raw}
path="/vast/projects/xenium_5k/data/jazzPanda_paper_dataset/Xenium_human_lung_cancer/"
hl_cancer =get_xenium_data(path=path, 
                           mtx_name = "cell_feature_matrix/", trans_name="transcripts.csv.gz", cells_name="cells.csv.gz")


una_tran = nrow(hl_cancer$trans_info[hl_cancer$trans_info$cell_id == "UNASSIGNED", ])
lqc_tran = nrow(hl_cancer$trans_info[hl_cancer$trans_info$qv <20, ])
hl_cancer$trans_info = hl_cancer$trans_info[hl_cancer$trans_info$cell_id != "UNASSIGNED" & 
                                                !(hl_cancer$trans_info$cell_id %in% hl_cancer$zero_cells) & 
                                                hl_cancer$trans_info$qv>=20, ]

data_nm  <- "xenium_hlc"
# load geenrated data
cluster_info = readRDS(here(data_path,paste0(data_nm, "_clusters.Rds")))
cluster_info$cell_id = row.names(cluster_info)
clusts <- unique(cluster_info$cluster)
cluster_names <- clusts[order(as.numeric(sub("c", "", clusts)))]
anno_df <- data.frame(
  cluster = c("c1","c2","c3","c4","c5","c6","c8","c9","c12","c13","c15","c16","c18"),
  major_class = c(
    "Myeloid","Lymphoid","Myeloid","Epithelial (tumor)","Stromal","Epithelial (non-malig.)",
    "Endothelial","Endothelial","Myeloid","Stromal","Lymphoid","Stromal","Epithelial (non-malig./mixed)"
  ),
  subclass = c(
    "Mononuclear phagocytes","T cells","Tissue-resident macrophages","Epithelial carcinoma",
    "Fibroblasts / CAFs","Secretory (airway/tracheobronchial)","Capillary/arterial endothelium",
    "Venous/HEV / lymphatic-skewed endothelium","Dendritic / inflammatory monocytes",
    "Smooth muscle (airway)","B lineage","Perivascular","Basal–ciliated airway lineage"
  ),
  specific_cell_type_state = c(
    "Activated TAM, CHIT1⁺/MMP^hi",
    "Activated/exhausted T cells (CD8⁺ GZMK⁺/PDCD1⁺) with Tfh/Treg admixture",
    "MARCO⁺/VSIG4⁺ alveolar-like macrophages (immunosuppressive)",
    "Lung adenocarcinoma cells (EPCAM⁺/MUC1⁺/EGFR⁺), cycling subset present",
    "Myofibroblastic CAFs (mCAFs)",
    "Club/Goblet-like secretory cells",
    "Capillary/arterial-like endothelium",
    "ACKR1⁺ venous/HEV-like endothelium with lymphatic features",
    "cDC2/Mono-DC (CD1C⁺/FCER1A⁺) + FCN1^hi monocytes",
    "Airway smooth muscle (ASM)",
    "Plasmablasts / plasma cells (MZB1⁺, CD27⁺, TNFRSF17⁺)",
    "Vascular smooth muscle / pericytes (MYH11⁺/CSPG4⁺)",
    "Basal/suprabasal & ciliated mixed program (SOX2/TP73/FOXJ1)"
  ),
  anno_name = c("Inflammatory TAM",
                "Activated T cell",
                "Alveolar macrophage",
                "Tumor epithelial",
                "Myofibroblast CAF",
                "Secretory epithelial",
                "Capillary endothelium",
                "Venous/HEV endothelium",
                "cDC2 / Mono-DC",
                "Airway smooth muscle",
                "Plasma cell",
                "Vascular SMC / Pericyte",
                "Basal–ciliated epithelium"), 
  evidence_selected_markers = c(
    "CHIT1, LGMN, AIF1, FCGR1A, ITGAM, CD14, MS4A4A; MMP9/12, CXCL10, TREM2/HAVCR2",
    "IL7R, CXCL9, GZMK/GZMA, PDCD1, CTLA4, CXCR6, CD3D/E, CD247; low FOXP3/CXCL13",
    "MARCO, VSIG4, CD163, FCGR3A, ALOX5, AQP9, CXCL5, RETN",
    "EPCAM, MUC1, KRT7, TACSTD2, EGFR, MET; UBE2C, TOP2A, MKI67, CENPF, CCNB2, AREG/SEC61G",
    "THBS2, SFRP2, LTBP2, COL5A2, COL8A1, FBN1, THY1, IGF1, PDPN; PDGFRA/B",
    "SFTPD, SFTA3, DMBT1, TMPRSS2, CFTR, GKN2, PEBP4, DUOX1, PRG4",
    "TMEM100, CA4, ACE, CLDN5, RAMP2, CD34, KCNK3; AGER present",
    "VWF, PLVAP, ACKR1, SELP, ADGRL4; LYVE1/PROX1 (low), ECSCR",
    "FCN1, S100A12, CD1C, FCER1A, CLEC4E, CD300E, CLEC10A",
    "DES, MYH11, CNN1, PLN, LMOD1; TGM2, FST",
    "MZB1, POU2AF1, CD79A, TNFRSF17, CD27, CD38, FKBP11",
    "MYH11 (very high), DES, CNN1, LMOD1, PLN; CSPG4, RERGL",
    "FOXJ1, MUC5B, KRT5, KRT17, KRT15, SOX2, TP73, CYP2F1, AGR3; ITGB4, ELF3"
  ),
  caveats_notes = c(
    "Mix of activation states; HPGDS/S100B hints mast/glial contamination; macrophage-dominant TAMs",
    "Multiple T states (CD8 effector, Tfh-like CXCL13, some FOXP3^lo Treg); could sub-stratify",
    "Classic lung alveolar macrophage signature; tissue-resident/immunoregulatory",
    "Strong epithelial oncogenic program; includes proliferative subset",
    "ECM-remodeling CAF program; mesenchymal; lacks strong iCAF chemokines",
    "Airways secretory program; likely non-malignant; check CNV to confirm",
    "AGER contamination from AT1 possible; endothelial program is clear",
    "Mixed venous/HEV signature; some lymphatic admixture; not capillary",
    "Mixture: cDC2 and FCN1^hi monocytes; separable by CD1C vs FCN1",
    "Smooth muscle core; co-exists with c16; lack of CSPG4 favors ASM",
    "Mature antibody-secreting program; MS4A1^low fits plasma bias",
    "Contractile SMC with CSPG4; vascular SMC/pericyte",
    "Mixed basal (KRT5/15/17, ITGB4) and ciliated (FOXJ1); continuum; may include squamous-like"
  ),
  stringsAsFactors = FALSE
)




cluster_info = merge(cluster_info, anno_df, by="cluster")

cluster_info$cluster = factor(cluster_info$cluster,
                              levels=cluster_names)

cluster_info$anno_name = factor(cluster_info$anno_name,
                              levels=anno_df$anno_name)
cluster_info = cluster_info[order(cluster_info$anno_name), ]


jazzPanda_res_lst = readRDS(here(data_path,paste0(data_nm, "_jazzPanda_res_lst.Rds")))

fit.cont = readRDS(here(data_path,paste0(data_nm, "_fit_cont_obj.Rds")))

perm_lst = readRDS(here(data_path,paste0(data_nm, "_perm_lst.Rds")))


FM_result= readRDS(here(data_path,paste0(data_nm, "_seu_markers.Rds")))
sv_lst = readRDS(here(data_path,paste0(data_nm, "_sq70_vector_lst.Rds")))
seu = readRDS(here(data_path,paste0(data_nm, "_seu.Rds")))
seu <- subset(seu, cells = cluster_info$cell_id)
nbins = 4900
Idents(seu)=cluster_info$anno_name[match(colnames(seu), cluster_info$cell_id)]
seu$sample = cluster_info$sample[match(colnames(seu), cluster_info$cell_id)]

```

```{r}
plot_data_sp(cluster_info=cluster_info,file_prefix = data_nm,fig_ratio=10/11,
             my_colors = my_colors, ct_nm = "anno_name")
plot_cluster_props(cluster_info=cluster_info,file_prefix = data_nm, 
                   my_colors = my_colors, ct_nm = "anno_name")

plot_umap_seu(cluster_info=cluster_info,seu=seu, file_prefix = data_nm, 
              my_colors = my_colors, ct_nm = "anno_name", fig_w = 1400)
```

# load blank genes
```{r negprobes, fig.width=8, fig.height=8 }

nc_coords <- hl_cancer$trans_info[(hl_cancer$trans_info$feature_name %in% 
                                        c(hl_cancer$probe, hl_cancer$codeword)), ]
nc_coords$category = "negative control probe"
nc_coords[nc_coords$feature_name %in% c(hl_cancer$codeword), "category"] = "negative control codeword"
cat("#negative controls", length(unique((nc_coords$feature_name))), "\n")
nc_coords$category=factor(nc_coords$category, 
                          levels =c("negative control probe",
                                   "negative control codeword"))
nc_coords$sample = "sample1"


# Xenium negative control category 
bins_map <- list("negative control probe" = 1,
                 "negative control codeword" = 1)   

plot_nc(nc_coords, "sample1","negative control probe" , 
        data_nm, overview_PA,fig_ratio=10/11,
          bins_map = bins_map, width = 1100, height = 1100)

plot_nc(nc_coords, "sample1", "negative control codeword", 
        data_nm, overview_PA,fig_ratio = 10/11,
          bins_map = bins_map, width = 1100, height = 1100)


```

# jazzPanda-correlation
```{r}
perm_res = get_perm_adjp(perm_lst)
obs_corr = get_cor(perm_lst)
```

## top3 marker genes by jazzPanda_correlation
```{r  top3-gene-vis-xy-corr, fig.width=10, fig.height=6}
for (cl in cluster_names){
    ct_nm = anno_df[anno_df$cluster==cl, "anno_name"]
    obs_cutoff = quantile(obs_corr[, cl], 0.75)
    perm_cl<-intersect(row.names(perm_res[perm_res[,cl]<0.05,]),
                     row.names(obs_corr[obs_corr[, cl]>obs_cutoff,]))
    inters<-perm_cl
    rounded_val<-signif(as.numeric(obs_corr[inters,cl]), digits = 3)
    inters_df = as.data.frame(cbind(gene=inters, value=rounded_val))
    inters_df$value = as.numeric(inters_df$value)
    inters_df<-inters_df[order(inters_df$value, decreasing = TRUE),]
    inters_df$text= paste(inters_df$gene,inters_df$value,sep=": ")
    
    if (length(inters > 0)){
        inters_df = inters_df[1:min(3, nrow(inters_df)),]
        inters = inters_df$gene
        iters_sp1= hl_cancer$trans_info$feature_name %in% inters
        vis_r1 =hl_cancer$trans_info[iters_sp1,
                        c("x","y","feature_name")]
        vis_r1$value = inters_df[match(vis_r1$feature_name,inters_df$gene),
                        "value"]
        vis_r1=vis_r1[order(vis_r1$value,decreasing = TRUE),]
        vis_r1$text_label= paste(vis_r1$feature_name,
                            vis_r1$value,sep=": ")
        vis_r1$text_label=factor(vis_r1$text_label, levels=inters_df$text)
    
        vis_r1 = vis_r1[order(vis_r1$text_label),]

        genes_plt<- ggplot(data = vis_r1,
                    aes(x = x, y = y))+ 
                    #geom_point(size=0.0001)+
                    geom_hex(bins = auto_hex_bin(mean(table(vis_r1$feature_name))))+
                    facet_wrap(~text_label, nrow=1)+
                    scale_fill_gradient(low="white", high="maroon4") + 
                    guides(fill = guide_colorbar(barheight = unit(0.3, "npc"), 
                                                 barwidth  = unit(0.02, "npc")))+
                    defined_theme+ theme(legend.position = "right", 
                              strip.background = element_rect(fill =NA,colour = NA),
                              strip.text = element_text(size = rel(1.3)), 
                              aspect.ratio = 10/11,
                              strip.text.y.right = element_blank(),
                              legend.key.width = unit(2, "cm"),
                              legend.title = element_text(size = 10),
                              legend.text = element_text(size = 10),
                               legend.key.height = unit(2, "cm"))
        
        cluster_data =  cluster_info[cluster_info$cluster==cl, ]
        cl_pt<- ggplot(data =cluster_data,
                    aes(x = x, y = y, color=sample))+ 
                    #geom_hex(bins = 100)+
                    geom_point(size=0.01)+
                    facet_wrap(~anno_name, nrow=1,strip.position = "left")+
                    scale_color_manual(values = c("black"))+
                    defined_theme + theme(legend.position = "none", 
                                          aspect.ratio = 10/11,
                              strip.background = element_blank(), 
                              legend.key.width = unit(15, "cm"),
                              strip.text = element_text(size = rel(1.3)))

        if (length(inters) == 2) {
            genes_plt <- (genes_plt | plot_spacer()) + 
            plot_layout(widths = c(2, 1))
        } else if (length(inters) == 1) {
            genes_plt <- (genes_plt | plot_spacer() | plot_spacer()) + 
            plot_layout(widths = c(1, 1, 1))
        } 
            
        lyt <- wrap_plots(cl_pt, ncol = 1) | genes_plt
        layout_design <- lyt + patchwork::plot_layout(widths = c(1, 3))
            
        cat("cluster:", cl,"\n")
        jpeg(file.path(mg_PA,paste0(data_nm, "_corr_", cl,"_top3.jpg")), 
             width=900*4, height=800, res=200)
        print(layout_design)
        dev.off()
    }
  }


```

## cluster vector versus marker gene vector 
```{r}
plot_lst=list()
for (cl in cluster_names){
    ct_nm = anno_df[anno_df$cluster==cl, "anno_name"]
    obs_cutoff = quantile(obs_corr[, cl], 0.75)
    perm_cl<-intersect(row.names(perm_res[perm_res[,cl]<0.05,]),
                     row.names(obs_corr[obs_corr[, cl]>obs_cutoff,]))
    inters<-perm_cl
    if (length(inters) >0){
        rounded_val<-signif(as.numeric(obs_corr[inters,cl]), digits = 3)
        inters_df = as.data.frame(cbind(gene=inters, value=rounded_val))
        inters_df$value = as.numeric(inters_df$value)
        inters_df<-inters_df[order(inters_df$value, decreasing = TRUE),]

        inters_df = inters_df[1:min(3, nrow(inters_df)),]
        mk_genes = inters_df$gene
        
        dff = as.data.frame(cbind(sv_lst$cluster_mt[,cl],
                          sv_lst$gene_mt[,mk_genes]))
        colnames(dff) = c("cluster", mk_genes)
        dff$vector_id = c(1:nbins)
        long_df <- dff %>% 
        pivot_longer(cols = -c(cluster, vector_id), names_to = "gene", 
           values_to = "vector_count")
        long_df$gene = factor(long_df$gene, levels=mk_genes)
        p<-ggplot(long_df, aes(x = cluster, y = vector_count, color=gene )) +
        geom_point(size=0.01) +
        facet_wrap(~gene, scales="free_y", nrow=1) +
        labs(x = paste(ct_nm, " cluster vector ", sep=""), 
        y = "Top3 marker gene vector") +
        theme_minimal()+
        scale_y_continuous(expand = c(0.01,0.01))+ 
        scale_x_continuous(expand =  c(0.01,0.01))+ 
        theme(panel.grid = element_blank(),
          legend.position = "none",
        strip.text = element_text(size = 12),
        axis.line=element_blank(),
        axis.text=element_text(size = 11),
        axis.ticks=element_line(color="black"),
        axis.title=element_text(size = 13),
        panel.border  =element_rect(colour = "black", 
                                fill=NA, linewidth=0.5)
        )
                
        if (length(mk_genes) == 2) {
            p <- (p | plot_spacer()) + 
            plot_layout(widths = c(2, 1))
        } else if (length(mk_genes) == 1) {
            p <- (p | plot_spacer() | plot_spacer()) + 
            plot_layout(widths = c(1, 1, 1))
        } 
        
        plot_lst[[cl]] = p
    }
}


combined_plot <- wrap_plots(plot_lst, ncol = 2)
jpeg(file.path(mg_PA, paste0(data_nm, "_corr_top3_vvplot.jpg")),
    height = 500 * (ceiling(length(plot_lst)/2)), width = 3000, res=200)
combined_plot 
dev.off()

```

# jazzPanda-glm
```{r jazzPanda-glm}
jazzPanda_res = get_top_mg(jazzPanda_res_lst, coef_cutoff=0.1)  
jazzPanda_summary = as.data.frame(table(jazzPanda_res$top_cluster))
colnames(jazzPanda_summary) = c("cluster","jazzPanda_glm")
```

```{r, output_markergenes, eval=FALSE}
# Combine into a new dataframe for LaTeX output
output_data <- do.call(rbind, lapply(cluster_names, function(cl) {
  subset <- jazzPanda_res[jazzPanda_res$top_cluster == cl, ]
  sorted_subset <- subset[order(-subset$glm_coef), ]
  gene_list <- paste(sorted_subset$gene, "(", 
                     round(sorted_subset$glm_coef, 2), ")", 
                     sep="", collapse=", ")
 
  return(data.frame(Cluster = cl, Genes = gene_list))
}))

latex_table <- xtable(output_data, caption="Detected marker genes for each cluster by jazzPanda, in decreasing value of glm coefficients")
print.xtable(latex_table, include.rownames = FALSE,
             hline.after = c(-1, 0, nrow(output_data)), comment = FALSE)
```
## top3 marker genes by jazzPanda_glm
```{r  top3-gene-vis-xy-glm, fig.width=10, fig.height=6}
for (cl in cluster_names){
    ct_nm = anno_df[anno_df$cluster==cl, "anno_name"]
    inters=jazzPanda_res[jazzPanda_res$top_cluster==cl,"gene"]
    rounded_val=signif(as.numeric(jazzPanda_res[inters,"glm_coef"]),
                          digits = 3)
    inters_df = as.data.frame(cbind(gene=inters, value=rounded_val))
    inters_df$value = as.numeric(inters_df$value)
    inters_df=inters_df[order(inters_df$value, decreasing = TRUE),]
    inters_df$text= paste(inters_df$gene,inters_df$value,sep=": ")
    
    if (length(inters > 0)){
        inters_df = inters_df[1:min(3, nrow(inters_df)),]
        inters = inters_df$gene
        iters_sp1= hl_cancer$trans_info$feature_name %in% inters
        vis_r1 =hl_cancer$trans_info[iters_sp1,
                        c("x","y","feature_name")]
        vis_r1$value = inters_df[match(vis_r1$feature_name,inters_df$gene),
                        "value"]
        vis_r1=vis_r1[order(vis_r1$value,decreasing = TRUE),]
        vis_r1$text_label= paste(vis_r1$feature_name,
                            vis_r1$value,sep=": ")
        vis_r1$text_label=factor(vis_r1$text_label, levels=inters_df$text)
    
        vis_r1 = vis_r1[order(vis_r1$text_label),]

        genes_plt<- ggplot(data = vis_r1,
                    aes(x = x, y = y))+ 
                    #geom_point(size=0.0001)+
                    geom_hex(bins = auto_hex_bin(mean(table(vis_r1$feature_name))))+
                    facet_wrap(~text_label, nrow=1)+
                    scale_fill_gradient(low="white", high="maroon4") + 
                    guides(fill = guide_colorbar(barheight = unit(0.3, "npc"), 
                                                 barwidth  = unit(0.02, "npc")))+
                    defined_theme+ 
            theme(legend.position = "right", 
                  aspect.ratio = 10/11,
                  strip.background = element_rect(fill =NA,colour = NA),
                  strip.text = element_text(size = rel(1.3)), 
                  strip.text.y.right = element_blank(),
                  legend.key.width = unit(2, "cm"),
                  legend.title = element_text(size = 10),
                  legend.text = element_text(size = 10),
                   legend.key.height = unit(2, "cm"))

        cluster_data =  cluster_info[cluster_info$cluster==cl, ]
        cl_pt<- ggplot(data =cluster_data,
                    aes(x = x, y = y, color=sample))+ 
                    #geom_hex(bins = 100)+
                    geom_point(size=0.01)+
                    facet_wrap(~anno_name, nrow=1,strip.position = "left")+
                    scale_color_manual(values = c("black"))+
                    defined_theme + theme(legend.position = "none", 
                              strip.background = element_blank(), 
                              legend.key.width = unit(15, "cm"),
                              aspect.ratio = 10/11,
                              strip.text = element_text(size = rel(1.3)))
        if (length(inters) == 2) {
            genes_plt <- (genes_plt | plot_spacer()) + 
            plot_layout(widths = c(2, 1))
        } else if (length(inters) == 1) {
            genes_plt <- (genes_plt | plot_spacer() | plot_spacer()) + 
            plot_layout(widths = c(1, 1, 1))
        } 
        
        lyt <- wrap_plots(cl_pt, ncol = 1) | genes_plt
        layout_design <- lyt + patchwork::plot_layout(widths = c(1, 3))
        
        cat("cluster:", cl,"\n")
        jpeg(file.path(mg_PA, paste0(data_nm, "_glm_", cl, "_top3.jpg")), 
             width=900*4, height=800, res=200)
        print(layout_design)
        dev.off()
    }
  }


```

## cluster vector versus marker gene vector 
```{r}
plot_lst=list()
for (cl in cluster_names){
     ct_nm = anno_df[anno_df$cluster==cl, "anno_name"]
    inters_df=jazzPanda_res[jazzPanda_res$top_cluster==cl,]
    
    if (nrow(inters_df) >0){
        inters_df=inters_df[order(inters_df$glm_coef, decreasing = TRUE),]
        
        inters_df = inters_df[1:min(3, nrow(inters_df)),]
        mk_genes = inters_df$gene
        dff = as.data.frame(cbind(sv_lst$cluster_mt[,cl],
                              sv_lst$gene_mt[,mk_genes]))
        colnames(dff) = c("cluster", mk_genes)
        dff$vector_id = c(1:nbins)
        long_df <- dff %>% 
        pivot_longer(cols = -c(cluster, vector_id), names_to = "gene", 
               values_to = "vector_count")
        long_df$gene = factor(long_df$gene, levels=mk_genes)
        p<-ggplot(long_df, aes(x = cluster, y = vector_count, color=gene )) +
        geom_point(size=0.01) +
        facet_wrap(~gene, scales="free_y", nrow=1) +
        labs(x = paste(ct_nm, " cluster vector ", sep=""), 
         y = "Top3 marker gene vector") +
        theme_minimal()+
        scale_y_continuous(expand = c(0.01,0.01))+ 
        scale_x_continuous(expand =  c(0.01,0.01))+ 
        theme(panel.grid = element_blank(),legend.position = "none",
        strip.text = element_text(size = 12),
        axis.line=element_blank(),
        axis.text=element_text(size = 11),
        axis.ticks=element_line(color="black"),
        axis.title=element_text(size = 13),
        panel.border  =element_rect(colour = "black", 
                                    fill=NA, linewidth=0.5)
        )
                
        if (length(mk_genes) == 2) {
            p <- (p | plot_spacer()) + 
            plot_layout(widths = c(2, 1))
        } else if (length(mk_genes) == 1) {
            p <- (p | plot_spacer() | plot_spacer()) + 
            plot_layout(widths = c(1, 1, 1))
        } 
        
        plot_lst[[cl]] = p
        
    }
    
}

combined_plot <- wrap_plots(plot_lst, ncol = 2)
jpeg(file.path(mg_PA,paste0(data_nm, "_glm_top3_vvplot.jpg")),
    height = 500 * (ceiling(length(plot_lst)/2)), width = 3000, res=200)
combined_plot 
dev.off()

```

# Compare marker genes by different methods
## FindMarker and limma result
```{r fm-mg, eval=FALSE}
table(FM_result$cluster)

FM_result$cluster <- factor(FM_result$cluster,
                            levels = cluster_names)

top_mg <- FM_result %>%
  group_by(cluster) %>%
  arrange(desc(avg_log2FC), .by_group = TRUE) %>% 
  slice_max(order_by = avg_log2FC, n = 10) %>%
  select(cluster, gene, avg_log2FC)

# Combine into a new dataframe for LaTeX output
output_data <- do.call(rbind, lapply(cluster_names, function(cl) {
  subset <- top_mg[top_mg$cluster == cl, ]
  sorted_subset <- subset[order(-subset$avg_log2FC), ]
  gene_list <- paste(sorted_subset$gene, "(", round(sorted_subset$avg_log2FC, 2), ")", sep="", collapse=", ")
 
  return(data.frame(Cluster = cl, Genes = gene_list))
}))
latex_table <- xtable(output_data, caption="Detected marker genes for each cluster by FindMarkers")
print.xtable(latex_table, include.rownames = FALSE, hline.after = c(-1, 0, nrow(output_data)), comment = FALSE)
```

```{r limma-mg}
limma_dt <- decideTests(fit.cont)
summary(limma_dt)
```

## Cumulative rank plot
```{r}
plot_lst=list()
cor_M = cor(sv_lst$gene_mt,
            sv_lst$cluster_mt[, cluster_names],
            method = "spearman")
cor_M[cor_M <= 0.7] = 0
cor_M[cor_M >  0.7]=1
Idents(seu)=cluster_info$cluster[match(colnames(seu), 
                                       cluster_info$cell_id)]
for (cl in cluster_names){
    ct_nm = anno_df[anno_df$cluster==cl, "anno_name"]
    
    fm_cl=FindMarkers(seu, ident.1 = cl, only.pos = TRUE,
            logfc.threshold = 0.25)
    fm_cl = fm_cl[order(fm_cl$avg_log2FC, decreasing = TRUE),]
    to_plot =row.names(fm_cl)
    if (length(to_plot)>0){
        FM_pt = data.frame("name"=to_plot,"rk"= 1:length(to_plot),
                       "y"= cumsum(cor_M[to_plot, cl]),
                       "type"="FindMarkers")
    }else{
        FM_pt <- data.frame(name = character(0), rk = integer(0), 
                               y= numeric(0), type = character(0))
    }

    limma_cl<-topTable(fit.cont,coef=cl,p.value = 0.05, n=Inf, sort.by = "p")
    limma_cl = limma_cl[limma_cl$logFC>0, ]
    to_plot_lm = row.names(limma_cl)
    if (length(to_plot_lm)>0){
        limma_pt <- data.frame("name"=to_plot_lm,"rk"= 1:length(to_plot_lm),
               "y"= cumsum(cor_M[to_plot_lm, cl]),
               "type"="limma")
    }else{
        limma_pt <- data.frame(name = character(0), rk = integer(0), 
                               y= numeric(0), type = character(0))
    }
    
    obs_cutoff = quantile(obs_corr[, cl], 0.75)
    perm_cl=intersect(row.names(perm_res[perm_res[,cl]<0.05,]),
                 row.names(obs_corr[obs_corr[, cl]>obs_cutoff,]))
    if (length(perm_cl) > 0) {
        rounded_val=signif(as.numeric(obs_corr[perm_cl,cl]), digits = 3)
        perm_sorted = as.data.frame(cbind(gene=perm_cl, value=rounded_val))
        perm_sorted$value = as.numeric(perm_sorted$value)
        perm_sorted=perm_sorted[order(perm_sorted$value, decreasing = TRUE),]
        
        corr_pt = data.frame("name"=perm_sorted$gene,
                             "rk"= 1:length(perm_sorted$gene),
                       "y"= cumsum(cor_M[perm_sorted$gene, cl]),
                       "type"="jazzPanda-correlation")
    } else {
      corr_pt <-data.frame(name = character(0), rk = integer(0), 
                               y= numeric(0), type = character(0))
    }
    
    lasso_sig = jazzPanda_res[jazzPanda_res$top_cluster==cl,]
    if (nrow(lasso_sig) > 0) {
        lasso_sig <- lasso_sig[order(lasso_sig$glm_coef, decreasing = TRUE), ]
        lasso_pt <- data.frame(
        name = lasso_sig$gene,
        rk   = seq_len(nrow(lasso_sig)),
        y    = cumsum(cor_M[lasso_sig$gene, cl]),
        type = "jazzPanda-glm"
        )
    } else {
      lasso_pt <- data.frame(name = character(0), rk = integer(0), 
                               y= numeric(0), type = character(0))
    }

    data_lst = rbind(limma_pt, FM_pt,corr_pt,lasso_pt)

    data_lst$type <- factor(
    data_lst$type,
    levels = c("limma", "FindMarkers", 
               "jazzPanda-correlation","jazzPanda-glm"),
    labels = c("limma", "Wilcoxon Rank Sum Test",
               "jazzPanda-correlation" ,"jazzPanda-glm")
    )
    data_lst$rk = as.numeric(data_lst$rk)
    p <-ggplot(data_lst, aes(x = rk, y = y, color = type)) +
        geom_step(size = 0.8) +  # type = "s"
        scale_color_manual(values = c("limma" = "black",
                                    "Wilcoxon Rank Sum Test" = "blue",
                                    "jazzPanda-correlation" = "orange",
                                    "jazzPanda-glm" = "red"
                                    )) +
        labs(title = ct_nm, x = "Rank of marker genes",
             y = "Cumulative count of genes with correlation >0.7",
             color = NULL) +
        theme_classic(base_size = 12) +
        theme(plot.title = element_text(hjust = 0.5),
            axis.line = element_blank(),  
            panel.border = element_rect(color = "black", 
                                        fill = NA, linewidth = 1),
            legend.position = "inside",
            legend.position.inside = c(0.98, 0.02),
            legend.justification = c("right", "bottom"),
            legend.background = element_rect(color = "black", 
                                             fill = "white", linewidth = 0.5),
            legend.box.background = element_rect(color = "black",
                                                 linewidth = 0.5)
        )
    plot_lst[[cl]] <- p
}


combined_plot <- wrap_plots(plot_lst, ncol = 4)
pdf(file.path(comp_PA, paste0(data_nm, "_mg_compare_rank.pdf")),
     height =4* (ceiling(length(cluster_names)/4)), width = 16)
combined_plot 
dev.off()

```
## upset plot
```{r upset-mg-comparison, fig.width=12, fig.height=18}
plot_lst=list()
for (cl in cluster_names){
    ct_nm = anno_df[anno_df$cluster==cl, "anno_name"]
    findM_sig <- FM_result[FM_result$cluster==cl,"gene"]
    limma_sig <- row.names(limma_dt[limma_dt[,cl]==1,])
    lasso_cl <- jazzPanda_res[jazzPanda_res$top_cluster==cl, "gene"]
    perm_cl <- intersect(row.names(perm_res[perm_res[,cl]<0.05,]),
                      row.names(obs_corr[obs_corr[, cl]>0.7,]))
    
    df_mt <- as.data.frame(matrix(FALSE,nrow=nrow(jazzPanda_res),ncol=4))
    row.names(df_mt) <- jazzPanda_res$gene
    colnames(df_mt) <- c("jazzPanda-glm",
                      "jazzPanda-correlation",
                      "Wilcoxon Rank Sum Test","limma")
    df_mt[findM_sig,"Wilcoxon Rank Sum Test"] <- TRUE
    df_mt[limma_sig,"limma"] <- TRUE
    df_mt[lasso_cl,"jazzPanda-glm"] <- TRUE
    df_mt[perm_cl,"jazzPanda-correlation"] <- TRUE
    
    df_mt$gene_name <- row.names(df_mt)
    
     p<-upset(df_mt,
              intersect=c("limma","Wilcoxon Rank Sum Test", 
                          "jazzPanda-correlation","jazzPanda-glm"),
              wrap=TRUE, keep_empty_groups= TRUE, name="",
              themes=theme_grey(),
              stripes=upset_stripes(geom=geom_segment(size=5),
                                    colors=c('grey95', 'grey95',
                                             'grey95','grey95')),
              sort_intersections_by ="cardinality", sort_sets= FALSE,min_degree=1,
              set_sizes=FALSE,
               sort_intersections= "descending", warn_when_converting=FALSE,
               warn_when_dropping_groups=TRUE,encode_sets=TRUE,
              matrix=(intersection_matrix()+
                          theme(axis.text.x=element_blank(),
                              panel.background = element_rect(fill="NA"),
                              axis.ticks = element_blank(),
                              axis.title = element_blank())),
              base_annotations=list('Intersection size'=(intersection_size(bar_number_threshold=1,color='grey9',fill='grey80')+
                scale_y_continuous(expand = expansion(mult = c(0, 0.15)))+
                theme(axis.text.x = element_blank(),axis.title.x = element_blank(),
                      panel.background = element_rect(fill="NA"),
                      panel.grid = element_line(color="grey90"),
                      axis.ticks.x = element_blank()))),
              width_ratio=0.5, height_ratio=1/4)+
           ggtitle(ct_nm)
        plot_lst[[cl]] <- p 
}

combined_plot <- wrap_plots(plot_lst, ncol = 4)
pdf(file.path(comp_PA,paste0(data_nm, "_mg_compare_upset.pdf")),
     height =4* (ceiling(length(cluster_names)/4)), width = 16)
combined_plot 
dev.off()
```

```{r}
sessionInfo()
```

