---
title: "Xenium human breast cancer samples"
author: "Melody Jin"
date: "2025-09-08"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: false
editor_options:
  chunk_output_type: console
---

```{r global-options, include = FALSE}
options(width = 80 , digits = 3) # output length

knitr::opts_chunk$set(cache = FALSE,echo = TRUE,prompt = FALSE, 
                      comment = NA,message = FALSE,warning = FALSE,
                      fig.align = "center", fig.keep= "all",fig.show ="hold")

```

```{r load-lib}
library(jazzPanda)
library(SpatialExperiment)
library(Seurat)
library(ggplot2)
library(data.table)
library(dplyr)
library(tidyr)
library(glmnet)
library(caret)
library(ComplexUpset)
library(ggrepel)
library(gridExtra)
library(patchwork)
library(RColorBrewer)
library(limma)
library(here)
library(data.table)
library(xtable)
source(here("scripts/utils.R"))

```

# load the data
```{r load-raw}
sp1_path <- "/vast/projects/xenium_5k/data/jazzPanda_paper_dataset/Xenium_human_breast_samples/Xenium_hbreast_sample1/"

sp1 = get_xenium_data(sp1_path, 
                      mtx_name="cell_feature_matrix",
                      trans_name="transcripts.csv.gz", 
                      cells_name="cells.csv.gz" )
sp1$trans_info = sp1$trans_info[sp1$trans_info$qv >=20 & 
                                    sp1$trans_info$cell_id != -1 & 
                                    !(sp1$trans_info$cell_id %in% sp1$zero_cells), ]

## sample2
sp2_path <- "/vast/projects/xenium_5k/data/jazzPanda_paper_dataset/Xenium_human_breast_samples/Xenium_hbreast_sample2/"
sp2 = get_xenium_data(sp2_path, 
                      mtx_name="cell_feature_matrix",
                      trans_name="transcripts.csv.gz", 
                      cells_name="cells.csv.gz" )

sp2$trans_info = sp2$trans_info[sp2$trans_info$qv >=20 & 
                                    sp2$trans_info$cell_id != -1 & 
                                    !(sp2$trans_info$cell_id %in% sp1$zero_cells), ]


data_nm  <- "xenium_hbreast"
# load geenrated data
cluster_info = readRDS(here(data_path,paste0(data_nm, "_clusters.Rds")))
colnames(cluster_info)[6] = "anno_name"

cluster_names = paste0("c", 1:9)
cluster_info$cluster = factor(cluster_info$cluster,
                              levels=cluster_names)
ct_names =c("Tumor", "Stromal","Macrophages","Myoepithelial", "T_Cells", 
            "B_Cells","Endothelial", "Dendritic", "Mast_Cells")
cluster_info$anno_name = factor(cluster_info$anno_name,
                          levels=ct_names)
rownames(cluster_info) <-cluster_info$cells
cluster_info = cluster_info[order(cluster_info$anno_name), ]
#cluster_info$cells = paste0("_", cluster_info$cells)
anno_df = unique(cluster_info[c("cluster", "anno_name")])
anno_df$anno_name = factor(anno_df$anno_name, levels = ct_names)
jazzPanda_res_lst = readRDS(here(data_path,paste0(data_nm, "_jazzPanda_res_lst.Rds")))

fit.cont = readRDS(here(data_path,paste0(data_nm, "_fit_cont_obj.Rds")))

FM_result= readRDS(here(data_path,paste0(data_nm, "_seu_markers.Rds")))

sv_lst = readRDS(here(data_path,paste0(data_nm, "_sq40_vector_lst.Rds")))
seu = readRDS(here(data_path,paste0(data_nm, "_seu.Rds")))
#seu <- subset(seu, cells = cluster_info$cells)
colnames(seu) <- sub("^_", "", colnames(seu))
colnames(seu) <- sub("_2$", "-sp2", colnames(seu))

Idents(seu) <- cluster_info$cluster[match(colnames(seu),
                                          cluster_info$cells)]

nbins = 1600

seu$sample = cluster_info$sample[match(colnames(seu), cluster_info$cells)]

```

```{r}
xhb_color<- c("#FC8D62","#66C2A5" ,"#8DA0CB","#E78AC3",
              "#A6D854","skyblue","purple3","#E5C498","blue")
plot_data_sp(cluster_info=cluster_info,file_prefix = data_nm, 
             my_colors = xhb_color, ct_nm = "anno_name",
             reverse_y = TRUE)
plot_cluster_props(cluster_info=cluster_info,file_prefix = data_nm, 
                   my_colors = xhb_color, ct_nm = "anno_name")

plot_umap_seu(cluster_info=cluster_info,seu=seu, file_prefix = data_nm, 
              my_colors = xhb_color, ct_nm = "anno_name", fig_w = 1400)
```

# load blank genes
```{r negprobes, fig.width=8, fig.height=8 }
nc_sp1 <- sp1$trans_info %>% 
    filter(feature_name %in% c(sp1$probe, sp1$codeword)) %>% 
    mutate(sample = "sample1", 
           category = ifelse(feature_name %in% sp1$codeword, 
                             "negative control codeword", 
                             "negative control probe"))


nc_sp2 <- sp2$trans_info %>% 
    filter(feature_name %in% c(sp2$probe, sp2$codeword)) %>% 
    mutate(sample = "sample2", 
           category = ifelse(feature_name %in% sp2$codeword, 
                             "negative control codeword",
                             "negative control probe"))

# Xenium negative control category 
bins_map <- list("negative control probe" = 2,
                 "negative control codeword" = 0.5)   

plot_nc(nc_sp1, "sample1","negative control probe" , 
        data_nm, fig2,reverse_y = TRUE,fig_ratio=5/7, 
          bins_map = bins_map, width = 700, height = 700)

plot_nc(nc_sp1, "sample1", "negative control codeword", 
        data_nm, overview_PA,reverse_y = TRUE,fig_ratio=5/7,
          bins_map = bins_map, width = 700, height = 700)
bins_map <- list("negative control probe" = 1,
                 "negative control codeword" = 0.5)
for (cat in unique(nc_sp2$category)) {
  plot_nc(nc_sp2, "sample2", cat, data_nm, overview_PA,
          reverse_y = TRUE,fig_ratio=5/7, 
          bins_map = bins_map, width = 700, height = 700)
}


```

# jazzPanda-glm
```{r jazzPanda-glm}
jazzPanda_res = get_top_mg(jazzPanda_res_lst, coef_cutoff=0.2)  
jazzPanda_summary = as.data.frame(table(jazzPanda_res$top_cluster))
colnames(jazzPanda_summary) = c("cluster","jazzPanda_glm")
```

```{r, output_markergenes, eval=FALSE}
# Combine into a new dataframe for LaTeX output
output_data <- do.call(rbind, lapply(cluster_names, function(cl) {
  subset <- jazzPanda_res[jazzPanda_res$top_cluster == cl, ]
  sorted_subset <- subset[order(-subset$glm_coef), ]
  gene_list <- paste(sorted_subset$gene, "(", 
                     round(sorted_subset$glm_coef, 2), ")", 
                     sep="", collapse=", ")
 
  return(data.frame(Cluster = cl, Genes = gene_list))
}))

latex_table <- xtable(output_data, caption="Detected marker genes for each cluster by jazzPanda, in decreasing value of glm coefficients")
print.xtable(latex_table, include.rownames = FALSE,
             hline.after = c(-1, 0, nrow(output_data)), comment = FALSE)
```
## top3 marker genes by jazzPanda_glm
```{r  top3-gene-vis-xy, fig.width=10, fig.height=6}
for (cl in cluster_names){
    ct_nm = anno_df[anno_df$cluster==cl, "anno_name"]
    inters=jazzPanda_res[jazzPanda_res$top_cluster==cl,"gene"]
    rounded_val=signif(as.numeric(jazzPanda_res[inters,"glm_coef"]),
                          digits = 3)
    inters_df = as.data.frame(cbind(gene=inters, value=rounded_val))
    inters_df$value = as.numeric(inters_df$value)
    inters_df=inters_df[order(inters_df$value, decreasing = TRUE),]
    inters_df$text= paste(inters_df$gene,inters_df$value,sep=": ")
    
    if (length(inters > 0)){
        inters_df = inters_df[1:min(3, nrow(inters_df)),]
        inters = inters_df$gene
        iters_sp1= sp1$trans_info$feature_name %in% inters
        vis_r1 =sp1$trans_info[iters_sp1,
                        c("x","y","feature_name")]
        vis_r1$value = inters_df[match(vis_r1$feature_name,inters_df$gene),
                        "value"]
        vis_r1$sample = "sample1"
        iters_sp2= sp2$trans_info$feature_name %in% inters
        vis_r2 =sp2$trans_info[iters_sp2,
                        c("x","y","feature_name")]
        vis_r2$value = inters_df[match(vis_r2$feature_name,inters_df$gene),
                        "value"]
        vis_r2$sample = "sample2"
        vis_df = rbind(vis_r1, vis_r2)
        vis_df$text_label= paste(vis_df$feature_name,
                            vis_df$value,sep=": ")
        vis_df$text_label=factor(vis_df$text_label, levels=inters_df$text)
    
        vis_df = vis_df[order(vis_df$text_label),]

        genes_plt<- ggplot(data = vis_df,
                    aes(x = x, y = y))+ 
                    scale_y_reverse()+
                    geom_hex(bins = auto_hex_bin(mean(table(vis_df$sample, 
                                                            vis_df$feature_name))))+
                    facet_grid(sample~text_label)+
                    scale_fill_gradient(low="white", high="maroon4") + 
                    guides(fill = guide_colorbar(barheight = unit(0.2, "npc"), 
                                                 barwidth  = unit(0.03, "npc")))+
                    defined_theme+ theme(legend.position = "right", 
                              strip.background = element_rect(fill =NA,colour = NA),
                              strip.text = element_text(size = rel(1.2)), 
                              strip.text.y.right = element_blank(),
                              legend.key.width = unit(2, "cm"),
                              fig_ratio=5/7,
                              legend.title = element_text(size = 10),
                              legend.text = element_text(size = 10),
                               legend.key.height = unit(2, "cm"))

        cluster_data =  cluster_info[cluster_info$cluster==cl, ]
        cluster_data$label = paste(cluster_data$sample, cluster_data$anno_name, sep="-")
        cluster_data$label =factor(cluster_data$label, 
                                   levels=c(paste0("sample1-", ct_nm), 
                                            paste0("sample2-",ct_nm )))
        cl_pt<- ggplot(data =cluster_data,
                    aes(x = x, y = y, color=sample))+ 
                    #geom_hex(bins = 100)+
                    geom_point(size=0.01)+
                    facet_wrap(~label, nrow=2,strip.position = "left")+
                    scale_y_reverse() +
                    scale_color_manual(values = c("black","black"))+
                    #scale_fill_gradient(low="white", high="maroon4") + 
                    #guides(fill = guide_colorbar(barwidth = unit(15, "cm"),height= unit(30, "cm")))+
                    defined_theme + 
            theme(legend.position = "none", fig_ratio=5/7,
                  strip.background = element_blank(), 
                  legend.key.width = unit(15, "cm"),
                  strip.text = element_text(size = rel(1.2)))

        if (length(inters) == 2) {
            genes_plt <- (genes_plt | plot_spacer()) + 
            plot_layout(widths = c(2, 1))
        } else if (length(inters) == 1) {
            genes_plt <- (genes_plt | plot_spacer() | plot_spacer()) + 
            plot_layout(widths = c(1, 1, 1))
        } 
        
        lyt <- wrap_plots(cl_pt, ncol = 1) | genes_plt
        layout_design <- lyt + patchwork::plot_layout(widths = c(1, 3))
        
        cat("cluster:", cl,"\n")
        jpeg(file.path(mg_PA, paste0(data_nm, "_glm_", cl, "_top3.jpg")), 
             width=700*4, height=500*2, res=200)
        print(layout_design)
        dev.off()
    }
  }


```

## cluster vector versus marker gene vector 
```{r}
plot_lst=list()
for (cl in cluster_names){
    ct_nm = anno_df[anno_df$cluster==cl, "anno_name"]
    inters_df=jazzPanda_res[jazzPanda_res$top_cluster==cl,]
    
    if (nrow(inters_df) >0){
        inters_df=inters_df[order(inters_df$glm_coef, decreasing = TRUE),]
        
        inters_df = inters_df[1:min(3, nrow(inters_df)),]
        mk_genes = inters_df$gene
        dff = as.data.frame(cbind(sv_lst$cluster_mt[,cl],
                              sv_lst$gene_mt[,mk_genes]))
        colnames(dff) = c("cluster", mk_genes)
        dff$vector_id = c(1:nbins, 1:nbins)
        dff$sample= "sample1"
        dff[nbins:(2*nbins),"sample"] = "sample2"
        long_df <- dff %>% 
        pivot_longer(cols = -c(cluster, vector_id, sample), names_to = "gene", 
               values_to = "vector_count")
        long_df$gene = factor(long_df$gene, levels=mk_genes)
        long_df$sample = factor(long_df$sample, levels=c("sample1", "sample2"))
        p<-ggplot(long_df, aes(x = cluster, y = vector_count, color=gene )) +
        geom_point(size=0.01) +
        facet_grid(sample~gene, scales="free_y") +
        labs(x = paste(ct_nm, " cluster vector ", sep=""), 
         y = "Top3 marker gene vector") +
        theme_minimal()+
        scale_y_continuous(expand = c(0.01,0.01))+ 
        scale_x_continuous(expand =  c(0.01,0.01))+ 
        theme(panel.grid = element_blank(),legend.position = "none",
        strip.text = element_text(size = 12),
        axis.line=element_blank(),
        axis.text=element_text(size = 11),
        axis.ticks=element_line(color="black"),
        axis.title=element_text(size = 13),
        panel.border  =element_rect(colour = "black", 
                                    fill=NA, linewidth=0.5)
        )
        
        if (length(mk_genes) == 2) {
            p <- (p | plot_spacer()) + 
            plot_layout(widths = c(2, 1))
        } else if (length(mk_genes) == 1) {
            p <- (p | plot_spacer() | plot_spacer()) + 
            plot_layout(widths = c(1, 1, 1))
        } 
        
        plot_lst[[cl]] = p
        
    }
    
}


n_per_page <- 6
rem <- length(plot_lst) %% n_per_page
if (rem != 0) {
  n_pad <- n_per_page - rem
  plot_lst <- c(
    plot_lst,
    rep(list(patchwork::plot_spacer()), n_pad)
  )
}

# Split into 2×2 pages
plot_chunks <- split(plot_lst, ceiling(seq_along(plot_lst) / n_per_page))

pdf(file.path(mg_PA, paste0(data_nm, "_glm_mg_vvplot.pdf")),
    height = 12, width = 12)

for (chunk in plot_chunks) {
  # arrange 2 columns, auto rows
   p <- wrap_plots(chunk, ncol = 2) +
       plot_layout(heights = c(1,1,1), widths = c(1,1))
  print(p)
}

dev.off()

```

# Compare marker genes by different methods
## FindMarker and limma result
```{r fm-mg, eval=FALSE}
table(FM_result$cluster)

FM_result$cluster <- factor(FM_result$cluster,
                            levels = cluster_names)

top_mg <- FM_result %>%
  group_by(cluster) %>%
  arrange(desc(avg_log2FC), .by_group = TRUE) %>% 
  slice_max(order_by = avg_log2FC, n = 10) %>%
  select(cluster, gene, avg_log2FC)

# Combine into a new dataframe for LaTeX output
output_data <- do.call(rbind, lapply(cluster_names, function(cl) {
  subset <- top_mg[top_mg$cluster == cl, ]
  sorted_subset <- subset[order(-subset$avg_log2FC), ]
  gene_list <- paste(sorted_subset$gene, "(", round(sorted_subset$avg_log2FC, 2), ")", sep="", collapse=", ")
 
  return(data.frame(Cluster = cl, Genes = gene_list))
}))
latex_table <- xtable(output_data, caption="Detected marker genes for each cluster by FindMarkers")
print.xtable(latex_table, include.rownames = FALSE, 
             hline.after = c(-1, 0, nrow(output_data)), comment = FALSE)
```

```{r limma-mg}
limma_dt <- decideTests(fit.cont)
summary(limma_dt)
```

## Cumulative rank plot
```{r}
plot_lst=list()
cor1 <- cor(sv_lst$gene_mt[1:1600, ],
            sv_lst$cluster_mt[1:1600, paste0("c", 1:9)], method = "spearman")

cor2 <- cor(sv_lst$gene_mt[1600:3200, ],
            sv_lst$cluster_mt[1600:3200, paste0("c", 1:9)], method = "spearman")

cor_M <-(cor1 + cor2) / 2

Idents(seu)=cluster_info$cluster[match(colnames(seu), 
                                       cluster_info$cells)]
for (cl in cluster_names){
    ct_nm = anno_df[anno_df$cluster==cl, "anno_name"]
    
    fm_cl=FindMarkers(seu, ident.1 = cl, only.pos = TRUE,
            logfc.threshold = 0.1)
    fm_cl = fm_cl[fm_cl$p_val_adj<0.05, ]
    fm_cl = fm_cl[order(fm_cl$avg_log2FC, decreasing = TRUE),]
    to_plot_fm =row.names(fm_cl)
    if (length(to_plot_fm)>0){
       FM_pt = data.frame("name"=to_plot_fm,"rk"= 1:length(to_plot_fm),
                       "y"= get_cmr_ma(to_plot_fm,cor_M = cor_M, cl = cl),
                       "type"="Wilcoxon Rank Sum Test")
    }else{
        FM_pt <- data.frame(name = character(0), rk = integer(0), 
                               y= numeric(0), type = character(0))
    }

    limma_cl<-topTable(fit.cont,coef=cl,p.value = 0.05, n=Inf, sort.by = "p")
    limma_cl = limma_cl[limma_cl$logFC>0, ]
    to_plot_lm = row.names(limma_cl)
    if (length(to_plot_lm)>0){
       limma_pt = data.frame("name"=to_plot_lm,"rk"= 1:length(to_plot_lm),
                      "y"= get_cmr_ma(to_plot_lm,cor_M = cor_M, cl = cl),
                      "type"="limma")
    }else{
        limma_pt <- data.frame(name = character(0), rk = integer(0), 
                               y= numeric(0), type = character(0))
    }
    
  
    lasso_sig = jazzPanda_res[jazzPanda_res$top_cluster==cl,]
    if (nrow(lasso_sig) > 0) {
        lasso_sig <- lasso_sig[order(lasso_sig$glm_coef, decreasing = TRUE), ]
        lasso_pt = data.frame("name"=lasso_sig$gene,"rk"= 1:nrow(lasso_sig),
                          "y"= get_cmr_ma(lasso_sig$gene,cor_M = cor_M, cl = cl),
                          "type"="jazzPanda-glm")
    
    } else {
      lasso_pt <- data.frame(name = character(0), rk = integer(0), 
                               y= numeric(0), type = character(0))
    }

    data_lst = rbind(limma_pt, FM_pt,lasso_pt)

    data_lst$type <- factor(
        data_lst$type,
        levels = c("jazzPanda-glm", "limma", "Wilcoxon Rank Sum Test")
    )
    data_lst$rk = as.numeric(data_lst$rk)
    p <-ggplot(data_lst, aes(x = rk, y = y, color = type)) +
        geom_step(size = 0.8) +  # type = "s"
        scale_color_manual(values = c("jazzPanda-glm" = "red",
                                      "limma" = "black",
                                      "Wilcoxon Rank Sum Test" = "blue")) +
        labs(title = ct_nm, x = "Rank of marker genes",
             y = "Cumulative average correlation",
             color = NULL) +
        scale_x_continuous(limits = c(0, 50))+
        theme_classic(base_size = 12) +
        theme(plot.title = element_text(hjust = 0.5),
            axis.line = element_blank(),  
            panel.border = element_rect(color = "black", 
                                        fill = NA, linewidth = 1),
            legend.position = "inside",
            legend.position.inside = c(0.98, 0.02),
            legend.justification = c("right", "bottom"),
            legend.background = element_rect(color = "black", 
                                             fill = "white", linewidth = 0.5),
            legend.box.background = element_rect(color = "black",
                                                 linewidth = 0.5)
        )
    plot_lst[[cl]] <- p
}


combined_plot <- wrap_plots(plot_lst, ncol = 4)
pdf(file.path(comp_PA, paste0(data_nm, "_mg_compare_rank.pdf")),
     height =4* (ceiling(length(cluster_names)/4)), width = 16)
combined_plot 
dev.off()

```
## upset plot
```{r upset-mg-comparison, fig.width=12, fig.height=18}
plot_lst=list()
for (cl in cluster_names){
    ct_nm = anno_df[anno_df$cluster==cl, "anno_name"]
    findM_sig <- FM_result[FM_result$cluster==cl & FM_result$p_val_adj<0.05,"gene"]
    limma_sig <- row.names(limma_dt[limma_dt[,cl]==1,])
    lasso_cl <- jazzPanda_res[jazzPanda_res$top_cluster==cl, "gene"]
    
    df_mt <- as.data.frame(matrix(FALSE,nrow=nrow(jazzPanda_res),ncol=3))
    row.names(df_mt) <- jazzPanda_res$gene
    colnames(df_mt) <- c("jazzPanda-glm",
                      "Wilcoxon Rank Sum Test","limma")
    df_mt[findM_sig,"Wilcoxon Rank Sum Test"] <- TRUE
    df_mt[limma_sig,"limma"] <- TRUE
    df_mt[lasso_cl,"jazzPanda-glm"] <- TRUE
    
    df_mt$gene_name <- row.names(df_mt)
    
    p = plot(upset(df_mt,
               intersect=c("Wilcoxon Rank Sum Test", "limma",
                           "jazzPanda-glm"),
               wrap=TRUE, keep_empty_groups= FALSE, name="",
               #themes=theme_grey(),
               stripes='white',
               sort_intersections_by ="cardinality", sort_sets= FALSE,min_degree=1,
               set_sizes =( 
                   upset_set_size()
                   + theme(axis.title= element_blank(),
                           axis.ticks.y = element_blank(),
                           axis.text.y = element_blank())),
               sort_intersections= "descending", warn_when_converting=FALSE,
               warn_when_dropping_groups=TRUE,encode_sets=TRUE,

               width_ratio=0.3, height_ratio=1/4)+
              ggtitle(ct_nm)+
                 theme(plot.title = element_text( size=15))

    )
          
    plot_lst[[cl]] <- p 
}

combined_plot <- wrap_plots(plot_lst, ncol = 4)
pdf(file.path(comp_PA,paste0(data_nm, "_mg_compare_upset.pdf")),
     height =5* (ceiling(length(cluster_names)/4)), width = 22)
combined_plot 
dev.off()
```

```{r}
sessionInfo()
```

