---
title: "Simulation details"
author: "Melody Jin"
date: "2025-09-17"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: false
editor_options:
  chunk_output_type: console
---

```{r}
library(ggplot2)
library(ggpubr)
library(ggrepel)
library(gridExtra)
library(matrixStats)
library(patchwork)
library(pheatmap)
library(Seurat)
library(RColorBrewer)
library(reshape2)
library(jazzPanda)
library(tidyr)
library(dplyr)
library(corrplot)
library(edgeR)
library(ComplexUpset)
library(dplyr)
library(spatstat)
library(here)
library(tidyverse)
source(here("scripts/utils.R"))
```

## cluster sizses versus number of significant genes 
```{r}

wk_path = here("scripts/main/cosmx_hlc_simulation_result/")

perm_res_files <- list.files(path =wk_path,
                          pattern = "^cosmx_hlc_simulation_s[0-9]+_perm_res_lst\\.Rds$",
                          full.names = TRUE)

p_value_lst <- list()

adjp_value_lst <- list()

obs_lst <- list()


# Loop over the files
for (f in perm_res_files) {
  res_obj <- readRDS(f)
  
  # Optionally extract the seed from the filename
  seed <- sub("^.*_s([0-9]+)_perm_res_lst\\.Rds$", "\\1", basename(f))
  
  # Add a column for the seed to keep track
  res_obj$perm.pval = as.data.frame(res_obj$perm.pval)
  res_obj$obs.stat = as.data.frame(res_obj$obs.stat)
  res_obj$obs.stat$seed <- seed
  res_obj$perm.pval.adj$seed <- seed
  res_obj$perm.pval$seed <- seed
  
  obs_lst[[length(obs_lst) + 1]] <- get_cor(res_obj)
  p_value_lst[[length(p_value_lst) + 1]] <- res_obj$perm.pval
  adjp_value_lst[[length(adjp_value_lst) + 1]] <- get_perm_adjp(res_obj)
}

# Combine into single data frames
obs_df <- do.call(rbind, obs_lst)
adjp_df <- do.call(rbind, adjp_value_lst)
p_value_df <- do.call(rbind, p_value_lst)

colSums(p_value_df[, 1:13] <0.05)
colSums(adjp_df[, 1:13] <0.05)

zz = rowSums(adjp_df[, 1:13] <0.05)

table(zz)


jazzPanda_perm = as.data.frame(matrix(0, nrow=ncol(obs_df), ncol=2))
colnames(jazzPanda_perm) = c("cluster","jazzPanda_correlation")
jazzPanda_perm$cluster = colnames(obs_df)

for (cl in paste("c", 1:13, sep="")){
    obs_cutoff=0.05
    #obs_cutoff = quantile(obs_df[, cl], 0.95)
    perm_cl=intersect(row.names(adjp_df[adjp_df[,cl]<0.05,]),
                     row.names(obs_df[obs_df[, cl]>obs_cutoff,]))
    jazzPanda_perm[jazzPanda_perm$cluster==cl,"jazzPanda_correlation"] = length(perm_cl)
}

cat("False positive rate =", (sum(jazzPanda_perm[,2])/10000*100),"%")
```

# Number of significant genes versus cluster size
```{r}

data_nm  <- "cosmx_hlc"
# load geenrated data
cluster_info = readRDS(here(data_path,paste0(data_nm, "_clusters.Rds")))
colnames(cluster_info)[colnames(cluster_info) == "anno"] <- "anno_name"

cluster_names = c("tumor_1","tumor_2","Macrophages",
                  "T", "Periportal.LSECs","Stellate.cells",
                  "B","Central.venous.LSECs","Cholangiocytes",
                  "Hep","Portal.endothelial.cells","NK.like.cells",
                  "Erthyroid.cells")
cluster_info$cluster_ref =  paste("c",as.numeric(factor(cluster_info$anno_name)), sep="")
cluster_info$cluster_ref =factor(cluster_info$cluster_ref , levels=paste("c",1:13, sep=""))

nsig_df = as.data.frame(colSums(adjp_df[, 1:13] <0.05))
colnames(nsig_df) = c("nsig")
nsig_df$cluster = row.names(nsig_df)

plt_dff = as.data.frame(table(cluster_info$cluster_ref))
colnames(plt_dff) = c("cluster", "ncells")
dff = merge(plt_dff, nsig_df, by="cluster")
dff$log_ncells = log10(dff$ncells)
cl_anno = as.data.frame(unique(cluster_info[,c("anno_name","cluster_ref")]))
colnames(cl_anno) = c("anno_name","cluster")
dff = merge(dff, cl_anno, by="cluster")
dff$cluster = as.character(dff$cluster)
dff$anno_name = as.character(dff$anno_name)
dff = rbind(dff, c("falsecode", 0, 0, 0, "falsecode"), 
            c("negprobe", 0, 0, 0, "negprobe"))
```



## pvalue versus correlation
```{r}

adjp_long <- adjp_df[, 1:13] %>%
  rownames_to_column("gene") %>%
  pivot_longer(-gene, names_to = "cluster", values_to = "p_adj")

obs_long <- obs_df[, 1:13] %>%
  rownames_to_column("gene") %>%
  pivot_longer(-gene, names_to = "cluster", 
               values_to = "statistic")

merged_df <- left_join(adjp_long, obs_long, by = c("gene", "cluster"))

merged_df <- merged_df %>%
  mutate(log_padj = -log10(p_adj),
         flag_low_effect = p_adj < 0.05 & statistic > 0.05)  
merged_df$label = "Not significant"
merged_df[merged_df$flag_low_effect==TRUE,"label"] ="Significant"
merged_df$label = factor(merged_df$label, 
                         levels=c("Significant", "Not significant"))
merged_df$cluster=factor(merged_df$cluster, levels = c(
  "c1", "c2", "c3", "c4", "c5", "c6", "c7", "c8", "c9", 
  "c10", "c11", "c12", "c13", "falsecode", "negprobe"
))


merged_df = merge(merged_df, dff[, c("cluster","anno_name")], by="cluster")


x_thresh <- 0.05
y_thresh <- -log10(0.05)

merged_df <- merged_df %>%
  mutate(
    quadrant = case_when(
      statistic <= x_thresh & log_padj >= y_thresh ~ "Q1",  # Top-left
      statistic >  x_thresh & log_padj >= y_thresh ~ "Q2",  # Top-right
      TRUE ~ "Other"
    )
  )
merged_df$anno_name = factor(merged_df$anno_name, levels =cluster_names)
merged_df = merged_df[order(merged_df$anno_name),]

anno_levels <- unique(merged_df$anno_name)

all_combos <- expand_grid(
  anno_name = anno_levels,
  quadrant = c("Q1", "Q2")
)

quad_counts <- merged_df %>%
    
  filter(quadrant %in% c("Q1", "Q2")) %>%

  group_by(anno_name, quadrant) %>%
         
  summarise(n = n(), .groups = "drop") %>%
 right_join(all_combos, by = c("anno_name", "quadrant")) %>%
  mutate(n = replace_na(n, 0))

label_positions <- data.frame(
  quadrant = c("Q1", "Q2"),
  x = c(-0.2, 0.1), 
  y = c(2.5, 2.5)     # Choose visually suitable positions
)


# Merge counts with positions
quad_counts <- quad_counts %>%
  left_join(label_positions, by = "quadrant")

jpeg(file.path(comp_PA, "pval_vs_correlation_scatter.jpg"), 
    width=2500, height=2000,res=200)
ggplot(merged_df, aes(x = statistic, y = log_padj,color=label)) +
  geom_point(alpha = 0.6, size=0.01) +
    facet_wrap(~anno_name, ncol=4)+
    scale_color_manual(values=c("steelblue","black"))+
    scale_y_continuous(breaks = c(0, 1,-log10(0.05), 2,3), 
                       labels = c("0","1","-log10(0.05)","2","3"))+
    scale_x_continuous(limits = c(-0.25, 0.2),
                       breaks = c(-0.25,-0.1, 0, 0.05, 0.1, 0.2), 
                       labels = c(-0.25,-0.1,0, 0.05, 0.1, 0.2))+
  geom_hline(yintercept = -log10(0.05), color = "grey", linetype = "dashed") +
  geom_vline(xintercept = 0.05, color = "grey", linetype = "dashed") +
    geom_label(data = quad_counts,
               aes(x = x, y = y, label = n), inherit.aes = FALSE, size = 4,
               label.size = 0.3, label.r = unit(0.1, "lines"), fill = "white",   
               color = "black"    ) +
  labs(x = "correlation", y = "-log10(adjusted p-value)"
       ) +
        guides(colour = guide_legend(override.aes = list(size=4,alpha=1)))+
  theme_minimal(base_size = 13) +
  theme(panel.border = element_rect(color = "black", 
                                    fill = NA, linewidth = 0.6),
    legend.position = "top", legend.title = element_blank(),
    legend.text = element_text(size = 15),
    axis.title = element_text(size = 16),
     strip.text = element_text(size =16),
    axis.text = element_text(size = 12),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(),
    plot.title = element_text(face = "bold", size = 14)
  )
dev.off()
```

